import type { AuthLocale } from '@gooseforum/react/i18n/auth'

const en = {
  title: 'Access groups', description: 'Control category visibility and membership with reusable groups.', create: 'New group', groups: 'Groups', systemGroupHint: 'System groups are managed by GooseForum.', noGroups: 'No access groups', noMatchingGroups: 'No matching groups', selectGroup: 'Select a group to continue.', systemGroup: 'System group', systemImmutable: 'This system group cannot be edited or have members managed manually.', enabled: 'Enabled', disabled: 'Disabled', members: 'Members', member: 'Member', pending: 'Pending', categoryPermissions: 'Category permissions', manageCategoryPermissions: 'Manage category permissions', permissionSummaryHint: 'Effective permissions for this group are configured by category.', category: 'Category', visibility: 'Visibility', capability: 'Capability', public: 'Public', restricted: 'Restricted', none: 'None', read: 'Read', reply: 'Reply', createTopics: 'Create topics', manage: 'Manage', searchGroups: 'Search groups…', refresh: 'Refresh', loading: 'Loading…', loadFailed: 'Failed to load access groups', retry: 'Retry', edit: 'Edit', delete: 'Delete', save: 'Save', saving: 'Saving…', cancel: 'Cancel', groupName: 'Group name', groupNamePlaceholder: 'For example: Core members', groupNameRequired: 'Enter a group name', joinMode: 'Join mode', inviteOnly: 'Invite only', application: 'Application', systemEveryone: 'Everyone', systemRegistered: 'Registered users', enabledHint: 'Disabled groups no longer grant access.', createGroup: 'Create access group', editGroup: 'Edit access group', groupFormHint: 'Choose how users join this group.', deleteGroupTitle: 'Delete access group', deleteGroupConfirm: 'Delete this access group? Its grants and memberships will be removed.', groupSaved: 'Access group saved', groupDeleted: 'Access group deleted', memberCount: 'members', pendingCount: 'pending', grantCount: 'category grants', memberHint: 'Add members directly or review pending applications.', username: 'Username or user ID', usernamePlaceholder: 'Enter a username or numeric ID', role: 'Role', roleMember: 'Member', roleManager: 'Manager', addMember: 'Add member', noMembers: 'No members in this group', active: 'Active', approve: 'Approve', reject: 'Reject', removeMember: 'Remove member', removeMemberTitle: 'Remove group member', removeMemberConfirm: 'Remove this member from the group?', memberSaved: 'Member saved', memberDeleted: 'Member removed', applicationApproved: 'Application approved', applicationRejected: 'Application rejected', saveFailed: 'Save failed', deleteFailed: 'Delete failed', status: 'Status', actions: 'Actions', joinInviteDescription: 'Only administrators and group managers can add members.', joinApplicationDescription: 'Users may apply to join; managers review applications.',
} as const

const zh: Record<keyof typeof en, string> = {
  title: '访问组', description: '通过可复用的用户组管理分类可见范围和成员。', create: '新建访问组', groups: '访问组', systemGroupHint: '系统访问组由 GooseForum 自动维护。', noGroups: '暂无访问组', noMatchingGroups: '没有匹配的访问组', selectGroup: '请选择一个访问组。', systemGroup: '系统组', systemImmutable: '系统组不可编辑，也不能手动管理成员。', enabled: '启用', disabled: '停用', members: '成员', member: '成员', pending: '待审核', categoryPermissions: '分类权限', manageCategoryPermissions: '管理分类权限', permissionSummaryHint: '此处展示该访问组在各分类中的实际权限。', category: '分类', visibility: '可见范围', capability: '权限级别', public: '公开', restricted: '受限', none: '无权限', read: '查看', reply: '回复', createTopics: '创建主题', manage: '管理', searchGroups: '搜索访问组…', refresh: '刷新', loading: '正在加载…', loadFailed: '访问组加载失败', retry: '重试', edit: '编辑', delete: '删除', save: '保存', saving: '保存中…', cancel: '取消', groupName: '访问组名称', groupNamePlaceholder: '例如：核心成员', groupNameRequired: '请输入访问组名称', joinMode: '加入方式', inviteOnly: '仅邀请', application: '申请加入', systemEveryone: '所有人', systemRegistered: '已登录用户', enabledHint: '停用后，该组不再授予访问权限。', createGroup: '新建访问组', editGroup: '编辑访问组', groupFormHint: '设置用户加入该访问组的方式。', deleteGroupTitle: '删除访问组', deleteGroupConfirm: '确定删除这个访问组吗？相关权限和成员关系也会被移除。', groupSaved: '访问组已保存', groupDeleted: '访问组已删除', memberCount: '名成员', pendingCount: '项待审核', grantCount: '项分类权限', memberHint: '直接添加成员，或审核用户的加入申请。', username: '用户名或用户 ID', usernamePlaceholder: '输入用户名或数字 ID', role: '角色', roleMember: '成员', roleManager: '管理员', addMember: '添加成员', noMembers: '该访问组暂无成员', active: '正常', approve: '通过', reject: '拒绝', removeMember: '移除成员', removeMemberTitle: '移除访问组成员', removeMemberConfirm: '确定将这位成员移出访问组吗？', memberSaved: '成员已保存', memberDeleted: '成员已移除', applicationApproved: '申请已通过', applicationRejected: '申请已拒绝', saveFailed: '保存失败', deleteFailed: '删除失败', status: '状态', actions: '操作', joinInviteDescription: '只有管理员和访问组管理员可以添加成员。', joinApplicationDescription: '用户可以申请加入，由管理员审核。',
}

const resources = {
  zh,
  en,
  ja: { ...en, title: 'アクセスグループ', create: '新規グループ', groups: 'グループ', members: 'メンバー', categoryPermissions: 'カテゴリー権限', save: '保存', cancel: 'キャンセル' },
  it: { ...en, title: 'Gruppi di accesso', create: 'Nuovo gruppo', groups: 'Gruppi', members: 'Membri', categoryPermissions: 'Permessi categorie', save: 'Salva', cancel: 'Annulla' },
} as const

export type AccessGroupTextKey = keyof typeof en

export function createAccessGroupText(locale: AuthLocale) {
  const dictionary = resources[locale]
  return (key: AccessGroupTextKey) => dictionary[key]
}
