import type { AuthLocale } from '@gooseforum/react/i18n/auth'

const resources = {
  zh: {
    console: '管理后台', dashboard: '仪表盘', users: '用户', roles: '角色', accessGroups: '访问组', categories: '分类', posts: '内容', links: '友情链接', sponsors: '赞助者', badges: '徽章', resources: '文件资源', records: '操作记录', settings: '设置', siteInfo: '站点信息', siteChrome: '站点外观', mail: '邮件', security: '安全', posting: '发帖', announcement: '公告', sensitive: '敏感词', openSite: '打开站点', search: '搜索分类…', addCategory: '新建分类', globalModerators: '全局版主', loading: '正在加载…', empty: '没有匹配的分类', name: '分类名称', slug: '标识', description: '描述', sort: '排序', color: '颜色', icon: '图标', actions: '操作', edit: '编辑', remove: '删除', save: '保存', cancel: '取消', saving: '保存中…', moderators: '版主', setModerator: '设置版主', access: '访问权限', visibility: '可见范围', addModerator: '添加版主', searchUser: '搜索用户名…', noUsers: '没有匹配用户', unrestricted: '公开', restricted: '受限', everyone: '所有人', none: '无权限', read: '查看', reply: '回复', create: '创建主题', manage: '管理', accessHint: '为每个访问组设置该分类的最高权限。', accessConflict: '该分类包含同时属于多个分类的主题，暂时不能设为受限。', legacyImages: '设为受限后，旧正文中的公开图片链接不会自动变为私有。', noAudience: '当前设置没有任何可查看该分类的用户。', loadFailed: '加载失败', saveFailed: '保存失败', confirmDelete: '确定删除这个分类吗？', confirmRemove: '确定移除这位版主吗？', categoryRequired: '请输入分类名称', notAvailable: '此页面尚未迁移，现有 Vue 后台仍可使用。', backToVue: '打开现有后台页面', status: '状态', active: '启用', disabled: '停用', categoryCount: '个分类', manageHint: '管理分类信息、版主和访问范围。', globalHint: '全局版主可以管理全部分类。', userId: '用户 ID', close: '关闭', categoryFormHint: '保持名称、URL 标识和展示信息清晰一致。', accessSaved: '访问权限已保存', categorySaved: '分类已保存', moderatorAdded: '版主已添加', moderatorRemoved: '版主已移除', categoryDeleted: '分类已删除', external: '外部链接', httpNotify: 'HTTP 通知', oidc: 'OIDC 提供方', oauth: 'OAuth',
  },
  en: {
    console: 'Admin Console', dashboard: 'Dashboard', users: 'Users', roles: 'Roles', accessGroups: 'Access groups', categories: 'Categories', posts: 'Posts', links: 'Links', sponsors: 'Sponsors', badges: 'Badges', resources: 'File resources', records: 'Audit log', settings: 'Settings', siteInfo: 'Site info', siteChrome: 'Site chrome', mail: 'Mail', security: 'Security', posting: 'Posting', announcement: 'Announcement', sensitive: 'Sensitive words', openSite: 'Open site', search: 'Search categories…', addCategory: 'New category', globalModerators: 'Global moderators', loading: 'Loading…', empty: 'No matching categories', name: 'Category name', slug: 'Slug', description: 'Description', sort: 'Sort', color: 'Color', icon: 'Icon', actions: 'Actions', edit: 'Edit', remove: 'Delete', save: 'Save', cancel: 'Cancel', saving: 'Saving…', moderators: 'Moderators', setModerator: 'Set moderator', access: 'Access', visibility: 'Visibility', addModerator: 'Add moderator', searchUser: 'Search username…', noUsers: 'No matching users', unrestricted: 'Public', restricted: 'Restricted', everyone: 'Everyone', none: 'None', read: 'Read', reply: 'Reply', create: 'Create topics', manage: 'Manage', accessHint: 'Set the highest category access level for each group.', accessConflict: 'This category contains topics assigned to multiple categories and cannot be restricted yet.', legacyImages: 'Existing public image links in old posts will not become private automatically.', noAudience: 'No group can read this category with the current settings.', loadFailed: 'Failed to load', saveFailed: 'Failed to save', confirmDelete: 'Delete this category?', confirmRemove: 'Remove this moderator?', categoryRequired: 'Enter a category name', notAvailable: 'This page has not moved yet; the existing Vue admin remains available.', backToVue: 'Open existing admin page', status: 'Status', active: 'Active', disabled: 'Disabled', categoryCount: 'categories', manageHint: 'Manage category details, moderators, and audience.', globalHint: 'Global moderators can manage every category.', userId: 'User ID', close: 'Close', categoryFormHint: 'Keep the name, URL slug, and presentation details consistent.', accessSaved: 'Access saved', categorySaved: 'Category saved', moderatorAdded: 'Moderator added', moderatorRemoved: 'Moderator removed', categoryDeleted: 'Category deleted', external: 'External', httpNotify: 'HTTP notifications', oidc: 'OIDC provider', oauth: 'OAuth',
  },
} as const

export type AdminTextKey = keyof typeof resources.en
const localeResources = {
  ...resources,
  ja: {
    ...resources.en,
    console: '管理コンソール', dashboard: 'ダッシュボード', users: 'ユーザー', roles: 'ロール', accessGroups: 'アクセスグループ', categories: 'カテゴリー', posts: '投稿', settings: '設定', search: 'カテゴリーを検索…', addCategory: 'カテゴリーを追加', globalModerators: '全体モデレーター', loading: '読み込み中…', empty: '該当するカテゴリーはありません', name: '名前', slug: 'スラッグ', description: '説明', sort: '並び順', color: '色', icon: 'アイコン', actions: '操作', edit: '編集', remove: '削除', save: '保存', cancel: 'キャンセル', saving: '保存中…', moderators: 'モデレーター', access: 'アクセス権', addModerator: 'モデレーターを追加', searchUser: 'ユーザー名を検索…', noUsers: '該当するユーザーはいません', unrestricted: '公開', restricted: '制限あり', everyone: '全員', none: '権限なし', read: '閲覧', reply: '返信', create: 'トピック作成', manage: '管理', loadFailed: '読み込みに失敗しました', saveFailed: '保存に失敗しました',
  },
  it: {
    ...resources.en,
    console: 'Console amministrativa', dashboard: 'Dashboard', users: 'Utenti', roles: 'Ruoli', accessGroups: 'Gruppi di accesso', categories: 'Categorie', posts: 'Contenuti', settings: 'Impostazioni', search: 'Cerca categorie…', addCategory: 'Nuova categoria', globalModerators: 'Moderatori globali', loading: 'Caricamento…', empty: 'Nessuna categoria trovata', name: 'Nome', slug: 'Slug', description: 'Descrizione', sort: 'Ordine', color: 'Colore', icon: 'Icona', actions: 'Azioni', edit: 'Modifica', remove: 'Elimina', save: 'Salva', cancel: 'Annulla', saving: 'Salvataggio…', moderators: 'Moderatori', access: 'Accesso', addModerator: 'Aggiungi moderatore', searchUser: 'Cerca nome utente…', noUsers: 'Nessun utente trovato', unrestricted: 'Pubblica', restricted: 'Limitata', everyone: 'Tutti', none: 'Nessuno', read: 'Lettura', reply: 'Risposta', create: 'Crea discussioni', manage: 'Gestione', loadFailed: 'Caricamento non riuscito', saveFailed: 'Salvataggio non riuscito',
  },
} as const

export function createAdminText(locale: AuthLocale) {
  const dictionary = localeResources[locale]
  return (key: AdminTextKey) => dictionary[key]
}
