import type { AuthLocale } from '@gooseforum/react/i18n/auth'

const en = {
  linksTitle: 'Links', linksDescription: 'Manage public link groups and entries.', newGroup: 'New group', refresh: 'Refresh', loading: 'Loading…', loadFailed: 'Failed to load configuration', retry: 'Retry', add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save', saving: 'Saving…', cancel: 'Cancel', groupName: 'Group name', groupHint: 'Choose a name, emoji, and accent color.', emoji: 'Emoji', color: 'Color', linkName: 'Link name', url: 'URL', description: 'Description', logoUrl: 'Logo URL', visible: 'Visible', visibleHint: 'Hidden links remain configured but do not appear publicly.', linkHint: 'Enter the destination and optional presentation details.', requiredGroup: 'Enter a group name', requiredLink: 'Enter both a link name and URL', deleteGroup: 'Delete group?', deleteLink: 'Delete link?', deleteGroupHint: 'All links in this group will also be removed.', deleteLinkHint: 'This link will be removed from the group.', emptyGroup: 'No links yet. Add the first link.', saved: 'Configuration saved', saveFailed: 'Failed to save configuration', totalLinks: 'links total', linkGuide: 'Link publishing', linkGuideText: 'Groups and enabled links appear on the public links page.', openPublish: 'Open publish page', safety: 'Notes', safety1: 'Use complete HTTPS URLs when possible.', safety2: 'Hidden links are retained when saving.', safety3: 'Drag groups and links to change their order.', sponsorsTitle: 'Sponsors', sponsorsDescription: 'Manage sponsor tiers and public sponsor-page content.', saveAll: 'Save all', sponsorName: 'Sponsor name', sponsorMessage: 'Message', sponsorLink: 'Sponsor link', sponsorHint: 'Enter sponsor presentation details.', requiredSponsor: 'Enter a sponsor name', newSponsor: 'Add sponsor', editSponsor: 'Edit sponsor', upload: 'Upload image', uploadFailed: 'Image upload failed', contentTitle: 'Page title', contentDescription: 'Page description', contact: 'Contact section', contactTitle: 'Contact title', contactDescription: 'Contact description', buttonText: 'Button text', buttonLink: 'Button link', rules: 'Rules', addRule: 'Add rule', noRules: 'No rules configured', removeRule: 'Remove rule', totalSponsors: 'sponsors total', level0: 'Diamond', level1: 'Gold', level2: 'Silver', level3: 'Bronze', emptyLevel: 'No sponsors in this tier.',
} as const

const zh: Record<keyof typeof en, string> = {
  linksTitle: '友情链接', linksDescription: '管理公开展示的链接分组和条目。', newGroup: '新建分组', refresh: '刷新', loading: '正在加载…', loadFailed: '配置加载失败', retry: '重试', add: '添加', edit: '编辑', delete: '删除', save: '保存', saving: '保存中…', cancel: '取消', groupName: '分组名称', groupHint: '设置分组名称、Emoji 和强调色。', emoji: 'Emoji', color: '颜色', linkName: '链接名称', url: 'URL', description: '描述', logoUrl: 'Logo URL', visible: '公开显示', visibleHint: '隐藏的链接仍会保留配置，但不会在公开页面展示。', linkHint: '填写目标地址和可选的展示信息。', requiredGroup: '请输入分组名称', requiredLink: '请输入链接名称和 URL', deleteGroup: '删除分组？', deleteLink: '删除链接？', deleteGroupHint: '该分组中的全部链接也会被移除。', deleteLinkHint: '该链接将从分组中移除。', emptyGroup: '暂无链接，添加第一个链接。', saved: '配置已保存', saveFailed: '配置保存失败', totalLinks: '个链接', linkGuide: '链接发布', linkGuideText: '分组和启用的链接会显示在公开友情链接页面。', openPublish: '打开发布页', safety: '注意事项', safety1: '尽量使用完整的 HTTPS 地址。', safety2: '隐藏链接在保存时仍会保留。', safety3: '拖动分组和链接可以调整顺序。', sponsorsTitle: '赞助者', sponsorsDescription: '管理赞助等级及公开赞助页面内容。', saveAll: '保存全部', sponsorName: '赞助者名称', sponsorMessage: '留言', sponsorLink: '赞助者链接', sponsorHint: '填写赞助者的展示信息。', requiredSponsor: '请输入赞助者名称', newSponsor: '添加赞助者', editSponsor: '编辑赞助者', upload: '上传图片', uploadFailed: '图片上传失败', contentTitle: '页面标题', contentDescription: '页面描述', contact: '联系区域', contactTitle: '联系标题', contactDescription: '联系描述', buttonText: '按钮文字', buttonLink: '按钮链接', rules: '规则', addRule: '添加规则', noRules: '暂无规则', removeRule: '删除规则', totalSponsors: '位赞助者', level0: '钻石', level1: '黄金', level2: '白银', level3: '青铜', emptyLevel: '该等级暂无赞助者。',
}

const resources = { zh, en, ja: { ...en, linksTitle: 'リンク', sponsorsTitle: 'スポンサー', save: '保存', cancel: 'キャンセル' }, it: { ...en, linksTitle: 'Link', sponsorsTitle: 'Sponsor', save: 'Salva', cancel: 'Annulla' } } as const
export type PageConfigTextKey = keyof typeof en
export function createPageConfigText(locale: AuthLocale) { const dictionary = resources[locale]; return (key: PageConfigTextKey) => dictionary[key] }
