/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsersManagementIndexRouteImport } from './routes/_authenticated/users-management/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSponsorshipManagementIndexRouteImport } from './routes/_authenticated/sponsorship-management/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRolesManagementIndexRouteImport } from './routes/_authenticated/roles-management/index'
import { Route as AuthenticatedPostsManagementIndexRouteImport } from './routes/_authenticated/posts-management/index'
import { Route as AuthenticatedLinksManagementIndexRouteImport } from './routes/_authenticated/links-management/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDashboardStatsIndexRouteImport } from './routes/_authenticated/dashboard-stats/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCategoriesManagementIndexRouteImport } from './routes/_authenticated/categories-management/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSiteSettingsSiteInfoIndexRouteImport } from './routes/_authenticated/site-settings/site-info/index'
import { Route as AuthenticatedSiteSettingsSecuritySettingsIndexRouteImport } from './routes/_authenticated/site-settings/security-settings/index'
import { Route as AuthenticatedSiteSettingsPostingSettingsIndexRouteImport } from './routes/_authenticated/site-settings/posting-settings/index'
import { Route as AuthenticatedSiteSettingsMailSettingsIndexRouteImport } from './routes/_authenticated/site-settings/mail-settings/index'
import { Route as AuthenticatedSiteSettingsFooterManagementIndexRouteImport } from './routes/_authenticated/site-settings/footer-management/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersManagementIndexRoute =
  AuthenticatedUsersManagementIndexRouteImport.update({
    id: '/users-management/',
    path: '/users-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSponsorshipManagementIndexRoute =
  AuthenticatedSponsorshipManagementIndexRouteImport.update({
    id: '/sponsorship-management/',
    path: '/sponsorship-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRolesManagementIndexRoute =
  AuthenticatedRolesManagementIndexRouteImport.update({
    id: '/roles-management/',
    path: '/roles-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsManagementIndexRoute =
  AuthenticatedPostsManagementIndexRouteImport.update({
    id: '/posts-management/',
    path: '/posts-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLinksManagementIndexRoute =
  AuthenticatedLinksManagementIndexRouteImport.update({
    id: '/links-management/',
    path: '/links-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStatsIndexRoute =
  AuthenticatedDashboardStatsIndexRouteImport.update({
    id: '/dashboard-stats/',
    path: '/dashboard-stats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesManagementIndexRoute =
  AuthenticatedCategoriesManagementIndexRouteImport.update({
    id: '/categories-management/',
    path: '/categories-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteSettingsSiteInfoIndexRoute =
  AuthenticatedSiteSettingsSiteInfoIndexRouteImport.update({
    id: '/site-settings/site-info/',
    path: '/site-settings/site-info/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteSettingsSecuritySettingsIndexRoute =
  AuthenticatedSiteSettingsSecuritySettingsIndexRouteImport.update({
    id: '/site-settings/security-settings/',
    path: '/site-settings/security-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteSettingsPostingSettingsIndexRoute =
  AuthenticatedSiteSettingsPostingSettingsIndexRouteImport.update({
    id: '/site-settings/posting-settings/',
    path: '/site-settings/posting-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteSettingsMailSettingsIndexRoute =
  AuthenticatedSiteSettingsMailSettingsIndexRouteImport.update({
    id: '/site-settings/mail-settings/',
    path: '/site-settings/mail-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteSettingsFooterManagementIndexRoute =
  AuthenticatedSiteSettingsFooterManagementIndexRouteImport.update({
    id: '/site-settings/footer-management/',
    path: '/site-settings/footer-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/categories-management': typeof AuthenticatedCategoriesManagementIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dashboard-stats': typeof AuthenticatedDashboardStatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/links-management': typeof AuthenticatedLinksManagementIndexRoute
  '/posts-management': typeof AuthenticatedPostsManagementIndexRoute
  '/roles-management': typeof AuthenticatedRolesManagementIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sponsorship-management': typeof AuthenticatedSponsorshipManagementIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users-management': typeof AuthenticatedUsersManagementIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/site-settings/footer-management': typeof AuthenticatedSiteSettingsFooterManagementIndexRoute
  '/site-settings/mail-settings': typeof AuthenticatedSiteSettingsMailSettingsIndexRoute
  '/site-settings/posting-settings': typeof AuthenticatedSiteSettingsPostingSettingsIndexRoute
  '/site-settings/security-settings': typeof AuthenticatedSiteSettingsSecuritySettingsIndexRoute
  '/site-settings/site-info': typeof AuthenticatedSiteSettingsSiteInfoIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/categories-management': typeof AuthenticatedCategoriesManagementIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dashboard-stats': typeof AuthenticatedDashboardStatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/links-management': typeof AuthenticatedLinksManagementIndexRoute
  '/posts-management': typeof AuthenticatedPostsManagementIndexRoute
  '/roles-management': typeof AuthenticatedRolesManagementIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sponsorship-management': typeof AuthenticatedSponsorshipManagementIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users-management': typeof AuthenticatedUsersManagementIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/site-settings/footer-management': typeof AuthenticatedSiteSettingsFooterManagementIndexRoute
  '/site-settings/mail-settings': typeof AuthenticatedSiteSettingsMailSettingsIndexRoute
  '/site-settings/posting-settings': typeof AuthenticatedSiteSettingsPostingSettingsIndexRoute
  '/site-settings/security-settings': typeof AuthenticatedSiteSettingsSecuritySettingsIndexRoute
  '/site-settings/site-info': typeof AuthenticatedSiteSettingsSiteInfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/categories-management/': typeof AuthenticatedCategoriesManagementIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/dashboard-stats/': typeof AuthenticatedDashboardStatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/links-management/': typeof AuthenticatedLinksManagementIndexRoute
  '/_authenticated/posts-management/': typeof AuthenticatedPostsManagementIndexRoute
  '/_authenticated/roles-management/': typeof AuthenticatedRolesManagementIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sponsorship-management/': typeof AuthenticatedSponsorshipManagementIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users-management/': typeof AuthenticatedUsersManagementIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/site-settings/footer-management/': typeof AuthenticatedSiteSettingsFooterManagementIndexRoute
  '/_authenticated/site-settings/mail-settings/': typeof AuthenticatedSiteSettingsMailSettingsIndexRoute
  '/_authenticated/site-settings/posting-settings/': typeof AuthenticatedSiteSettingsPostingSettingsIndexRoute
  '/_authenticated/site-settings/security-settings/': typeof AuthenticatedSiteSettingsSecuritySettingsIndexRoute
  '/_authenticated/site-settings/site-info/': typeof AuthenticatedSiteSettingsSiteInfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/categories-management'
    | '/chats'
    | '/dashboard-stats'
    | '/help-center'
    | '/links-management'
    | '/posts-management'
    | '/roles-management'
    | '/settings/'
    | '/sponsorship-management'
    | '/tasks'
    | '/users-management'
    | '/users'
    | '/site-settings/footer-management'
    | '/site-settings/mail-settings'
    | '/site-settings/posting-settings'
    | '/site-settings/security-settings'
    | '/site-settings/site-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/categories-management'
    | '/chats'
    | '/dashboard-stats'
    | '/help-center'
    | '/links-management'
    | '/posts-management'
    | '/roles-management'
    | '/settings'
    | '/sponsorship-management'
    | '/tasks'
    | '/users-management'
    | '/users'
    | '/site-settings/footer-management'
    | '/site-settings/mail-settings'
    | '/site-settings/posting-settings'
    | '/site-settings/security-settings'
    | '/site-settings/site-info'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/categories-management/'
    | '/_authenticated/chats/'
    | '/_authenticated/dashboard-stats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/links-management/'
    | '/_authenticated/posts-management/'
    | '/_authenticated/roles-management/'
    | '/_authenticated/settings/'
    | '/_authenticated/sponsorship-management/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users-management/'
    | '/_authenticated/users/'
    | '/_authenticated/site-settings/footer-management/'
    | '/_authenticated/site-settings/mail-settings/'
    | '/_authenticated/site-settings/posting-settings/'
    | '/_authenticated/site-settings/security-settings/'
    | '/_authenticated/site-settings/site-info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users-management/': {
      id: '/_authenticated/users-management/'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AuthenticatedUsersManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sponsorship-management/': {
      id: '/_authenticated/sponsorship-management/'
      path: '/sponsorship-management'
      fullPath: '/sponsorship-management'
      preLoaderRoute: typeof AuthenticatedSponsorshipManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles-management/': {
      id: '/_authenticated/roles-management/'
      path: '/roles-management'
      fullPath: '/roles-management'
      preLoaderRoute: typeof AuthenticatedRolesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts-management/': {
      id: '/_authenticated/posts-management/'
      path: '/posts-management'
      fullPath: '/posts-management'
      preLoaderRoute: typeof AuthenticatedPostsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links-management/': {
      id: '/_authenticated/links-management/'
      path: '/links-management'
      fullPath: '/links-management'
      preLoaderRoute: typeof AuthenticatedLinksManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-stats/': {
      id: '/_authenticated/dashboard-stats/'
      path: '/dashboard-stats'
      fullPath: '/dashboard-stats'
      preLoaderRoute: typeof AuthenticatedDashboardStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories-management/': {
      id: '/_authenticated/categories-management/'
      path: '/categories-management'
      fullPath: '/categories-management'
      preLoaderRoute: typeof AuthenticatedCategoriesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings/site-info/': {
      id: '/_authenticated/site-settings/site-info/'
      path: '/site-settings/site-info'
      fullPath: '/site-settings/site-info'
      preLoaderRoute: typeof AuthenticatedSiteSettingsSiteInfoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings/security-settings/': {
      id: '/_authenticated/site-settings/security-settings/'
      path: '/site-settings/security-settings'
      fullPath: '/site-settings/security-settings'
      preLoaderRoute: typeof AuthenticatedSiteSettingsSecuritySettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings/posting-settings/': {
      id: '/_authenticated/site-settings/posting-settings/'
      path: '/site-settings/posting-settings'
      fullPath: '/site-settings/posting-settings'
      preLoaderRoute: typeof AuthenticatedSiteSettingsPostingSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings/mail-settings/': {
      id: '/_authenticated/site-settings/mail-settings/'
      path: '/site-settings/mail-settings'
      fullPath: '/site-settings/mail-settings'
      preLoaderRoute: typeof AuthenticatedSiteSettingsMailSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-settings/footer-management/': {
      id: '/_authenticated/site-settings/footer-management/'
      path: '/site-settings/footer-management'
      fullPath: '/site-settings/footer-management'
      preLoaderRoute: typeof AuthenticatedSiteSettingsFooterManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCategoriesManagementIndexRoute: typeof AuthenticatedCategoriesManagementIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDashboardStatsIndexRoute: typeof AuthenticatedDashboardStatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLinksManagementIndexRoute: typeof AuthenticatedLinksManagementIndexRoute
  AuthenticatedPostsManagementIndexRoute: typeof AuthenticatedPostsManagementIndexRoute
  AuthenticatedRolesManagementIndexRoute: typeof AuthenticatedRolesManagementIndexRoute
  AuthenticatedSponsorshipManagementIndexRoute: typeof AuthenticatedSponsorshipManagementIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersManagementIndexRoute: typeof AuthenticatedUsersManagementIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedSiteSettingsFooterManagementIndexRoute: typeof AuthenticatedSiteSettingsFooterManagementIndexRoute
  AuthenticatedSiteSettingsMailSettingsIndexRoute: typeof AuthenticatedSiteSettingsMailSettingsIndexRoute
  AuthenticatedSiteSettingsPostingSettingsIndexRoute: typeof AuthenticatedSiteSettingsPostingSettingsIndexRoute
  AuthenticatedSiteSettingsSecuritySettingsIndexRoute: typeof AuthenticatedSiteSettingsSecuritySettingsIndexRoute
  AuthenticatedSiteSettingsSiteInfoIndexRoute: typeof AuthenticatedSiteSettingsSiteInfoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCategoriesManagementIndexRoute:
    AuthenticatedCategoriesManagementIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDashboardStatsIndexRoute: AuthenticatedDashboardStatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLinksManagementIndexRoute:
    AuthenticatedLinksManagementIndexRoute,
  AuthenticatedPostsManagementIndexRoute:
    AuthenticatedPostsManagementIndexRoute,
  AuthenticatedRolesManagementIndexRoute:
    AuthenticatedRolesManagementIndexRoute,
  AuthenticatedSponsorshipManagementIndexRoute:
    AuthenticatedSponsorshipManagementIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersManagementIndexRoute:
    AuthenticatedUsersManagementIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedSiteSettingsFooterManagementIndexRoute:
    AuthenticatedSiteSettingsFooterManagementIndexRoute,
  AuthenticatedSiteSettingsMailSettingsIndexRoute:
    AuthenticatedSiteSettingsMailSettingsIndexRoute,
  AuthenticatedSiteSettingsPostingSettingsIndexRoute:
    AuthenticatedSiteSettingsPostingSettingsIndexRoute,
  AuthenticatedSiteSettingsSecuritySettingsIndexRoute:
    AuthenticatedSiteSettingsSecuritySettingsIndexRoute,
  AuthenticatedSiteSettingsSiteInfoIndexRoute:
    AuthenticatedSiteSettingsSiteInfoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
