root = "."
tmp_dir = "storage/tmp"

[build]
  bin = "./storage/tmp/main serve"
  cmd = "go build -o ./storage/tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor","actor","web","storage"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html","env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
