[app]
name = "app"
env = "production" # APP_ENV in local,production
debug = true

[server]
url = "http://localhost"
port = 99

[db]
migration = "on" # OPEN_MIGRATION in on,off
[db.default]
connection = "sqlite"# in mysql sqlite
url = "db_user:db_pass@tcp(db_host:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local"
path = "./storage/database/sqlite.db"# :memory:|./storage/database/sqlite.db

maxIdleConnections = 50
maxOpenConnections = 50
maxLifeSeconds = 300

[log]
type = "stdout"# LOG_TYPE stdout,file
path = "./storage/logs/run.log"
rolling = false # 是否开启滚动 true ,false
maxage = 10 # 最大日期
maxsize = 256 # 最大文件大小 MB
maxBackUps = 30 # 最大保留文件数量

[PATH]
hexo = ""
workspace = ""
