import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('edits account restrictions in the existing flat user manager', async ({ page }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00Z'))
  await page.route('**/__goose_page/**', route => route.fulfill({ json: {
    component:'admin.shell', props:{}, url:'/admin/users?lang=en', version:'1.0',meta:{title:'Users'},
    layout:{site:{name:'GooseForum',description:'',logo:'',favicon:'',brandType:'default',brandText:'',brandImage:''},viewer:{id:1,username:'admin',email:'admin@example.com',avatarUrl:'',isAuthenticated:true,canAccessAdmin:true,isModerator:false,requiresEmailVerification:false,adminPermissions:[0]},header:[],sidebar:{activeKey:'topics',categories:[]},footer:{links:[],primary:[]},unread:{notifications:false,messages:false},theme:{enabled:false,current:'gf-light',themeColor:'#fbfdff'}}
  } }))
  const member = { userId:7,username:'alice',email:'alice@example.com',avatarUrl:'',status:1,restrictionStatus:'suspended',restrictionReason:'Repeated unsolicited posts',restrictionNote:'Reviewed by administrator',validate:1,prestige:10,roleId:0,roleList:[],createTime:'2026-10-03',lastActiveTime:'2026-10-03',badges:[] }
  await page.route('**/api/admin/user-mfa-status', route => route.fulfill({ json: { code: 0, result: { enabled: true } } }))
  let resetRequest: Record<string, unknown> | undefined
  await page.route('**/api/admin/user-mfa-reset', route => { resetRequest = route.request().postDataJSON(); return route.fulfill({ json: { code: 0, result: null } }) })
  await page.route('**/api/admin/user-list', route => route.fulfill({ json:{code:0,result:{list:[member],page:1,pageSize:10,total:1}} }))
  await page.route('**/api/admin/get-all-role-item', route => route.fulfill({ json:{code:0,result:[]} }))
  const badgeOptions = Array.from({length:5}, (_, index) => ({code:`badge-${index + 1}`,name:`Badge ${index + 1}`,description:`Badge ${index + 1}`,iconUrl:'/static/badges/contributor.svg'}))
  await page.route('**/api/admin/user-badge-options', route => route.fulfill({ json:{code:0,result:{options:badgeOptions,active:[]}} }))
  await page.route('**/api/admin/user-restriction-history**', route => route.fulfill({ json:{code:0,result:{list:[{id:1,userId:7,actorId:1,status:'suspended',reason:member.restrictionReason,note:member.restrictionNote,createdAt:'2026-10-03T00:00:00Z'}],page:1,pageSize:10,total:1}} }))
  let saved: Record<string,unknown> | undefined
  let savedBadges: Record<string,unknown> | undefined
  await page.route('**/api/admin/user-edit', route => { saved = route.request().postDataJSON(); return route.fulfill({ json:{code:0,result:'success'} }) })
  await page.route('**/api/admin/save-user-badges', route => { savedBadges = route.request().postDataJSON(); return route.fulfill({json:{code:0,result:'success'}}) })
  await page.goto('/admin/users?lang=en')
  await page.getByRole('button', { name:'Edit user' }).filter({visible:true}).first().click()
  const dialog = page.getByRole('dialog', {name:'Edit user', exact:true})
  await expect(dialog.getByRole('tab', {name:'Account', exact:true})).toHaveAttribute('data-state', 'active')
  await expect(dialog.getByLabel('Role', {exact:true})).toBeVisible()
  await dialog.getByRole('button', { name: 'Reset two-factor authentication', exact: true }).click()
  const resetDialog = page.getByRole('dialog', { name: 'Reset two-factor authentication · alice', exact: true })
  await expect(resetDialog.getByRole('button', { name: 'Reset two-factor authentication', exact: true })).toBeDisabled()
  await resetDialog.getByLabel('Identity verification and reset reason').fill('Identity verified')
  await resetDialog.getByRole('button', { name: 'Reset two-factor authentication', exact: true }).click()
  await expect(resetDialog).toHaveCount(0)
  expect(resetRequest).toEqual({ userId: 7, reason: 'Identity verified' })
  await expect(dialog.getByText('Not enabled', { exact: true })).toBeVisible()
  if (testInfo.project.name === 'chromium') {
    const body = dialog.locator('.overflow-y-auto')
    expect(await body.evaluate(element => element.scrollHeight - element.clientHeight)).toBeLessThanOrEqual(1)
  }
  await testInfo.attach('compact-user-editor',{body:await page.screenshot({path:`/tmp/gooseforum-user-editor-${testInfo.project.name}.png`}),contentType:'image/png'})
  await dialog.getByRole('tab', {name:'Badges', exact:true}).click()
  if (testInfo.project.name === 'chromium') {
    await expect(dialog.getByRole('button', {name:'Badge 5', exact:true})).toBeVisible()
    const firstBadge = await dialog.getByRole('button', {name:'Badge 1', exact:true}).boundingBox()
    const lastBadge = await dialog.getByRole('button', {name:'Badge 5', exact:true}).boundingBox()
    expect(Math.abs(firstBadge!.y - lastBadge!.y)).toBeLessThanOrEqual(1)
    const body = dialog.locator('.overflow-y-auto')
    expect(await body.evaluate(element => element.scrollHeight - element.clientHeight)).toBeLessThanOrEqual(1)
  }
  await testInfo.attach('user-badges',{body:await page.screenshot({path:`/tmp/gooseforum-user-badges-${testInfo.project.name}.png`}),contentType:'image/png'})
  await dialog.getByRole('tab', {name:'History', exact:true}).click()
  await expect(dialog.getByRole('heading',{name:'Restriction history'})).toBeVisible()
  await expect(dialog.getByRole('listitem').getByText(member.restrictionReason, {exact:true})).toBeVisible()
  await dialog.getByRole('button', {name:'Cancel', exact:true}).click()
  await page.route('**/api/admin/user-restriction-history**', route => {
    const currentPage = Number(new URL(route.request().url()).searchParams.get('page'))
    const list = Array.from({length:currentPage === 2 ? 1 : 10}, (_, index) => ({id:(currentPage - 1) * 10 + index + 1,userId:7,actorId:1,status:'suspended',reason:`History page ${currentPage}, item ${index + 1}`,createdAt:'2026-10-03T00:00:00Z'}))
    return route.fulfill({json:{code:0,result:{list,page:currentPage,pageSize:10,total:11}}})
  })
  await page.getByRole('button', {name:'Edit user'}).filter({visible:true}).first().click()
  await dialog.getByRole('tab', {name:'History', exact:true}).click()
  await dialog.getByRole('button', {name:'Next', exact:true}).click()
  await expect(dialog.getByText('History page 2, item 1', {exact:true})).toBeVisible()
  expect(saved).toBeUndefined()
  await expect(dialog.getByRole('button', {name:'Save changes'})).toBeInViewport()
  await dialog.getByRole('button', {name:'Previous', exact:true}).click()
  await expect(dialog.getByText('History page 1, item 1', {exact:true})).toBeVisible()
  expect(saved).toBeUndefined()
  await dialog.getByRole('tab', {name:'Account', exact:true}).click()
  await expect(dialog.getByLabel('Private administrator note')).toHaveCount(0)
  await dialog.getByLabel('Status',{exact:true}).click()
  await page.getByRole('option',{name:'Banned',exact:true}).click()
  const deadline = dialog.getByLabel('Restricted until')
  await expect(deadline).toHaveAttribute('data-slot', 'date-picker-trigger')
  await deadline.click()
  const datePicker = page.locator('[data-slot="date-picker-content"][data-state="open"]')
  await datePicker.locator('[data-day="10/6/2026"]').click()
  await datePicker.getByLabel('Time', {exact:true}).fill('10:00')
  await testInfo.attach('restriction-date-picker',{body:await page.screenshot({path:`/tmp/gooseforum-restriction-date-picker-${testInfo.project.name}.png`}),contentType:'image/png'})
  expect((await new AxeBuilder({page}).include('[data-slot="date-picker-content"]').withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze()).violations).toEqual([])
  await datePicker.getByRole('button', {name:'Done', exact:true}).click()
  expect(saved).toBeUndefined()
  await dialog.getByLabel('Restriction reason').fill('Repeated spam after warning')
  await dialog.getByRole('tab', {name:'Badges', exact:true}).click()
  await dialog.getByRole('button', {name:'Badge 1', exact:true}).click()
  await dialog.getByRole('tab', {name:'Account', exact:true}).click()
  await expect(dialog.getByLabel('Restriction reason')).toHaveValue('Repeated spam after warning')
  await expect(deadline).toContainText('Oct 6, 2026')
  await expect(dialog.getByText('Private administrator note: Reviewed by administrator',{exact:true})).toHaveCount(0)
  expect(await dialog.evaluate(element => element.scrollWidth > element.clientWidth + 1)).toBe(false)
  await testInfo.attach('account-restriction-editor',{body:await page.screenshot({fullPage:false,path:`/tmp/gooseforum-account-restriction-${testInfo.project.name}.png`}),contentType:'image/png'})
  const accessibility = await new AxeBuilder({page}).include('[role="dialog"]').withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze()
  expect(accessibility.violations).toEqual([])
  await dialog.getByRole('button',{name:'Save changes'}).click()
  await expect(dialog).toBeHidden()
  expect(saved).toMatchObject({userId:7,restrictionStatus:'banned',restrictionReason:'Repeated spam after warning',status:1})
  expect(saved?.restrictionUntil).toBeTruthy()
  expect(saved?.restrictionUntil).toBe(new Date('2026-10-06T10:00').toISOString())
  expect(savedBadges).toMatchObject({userId:7,badgeCodes:['badge-1']})
})
