package oidcprovider

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"strings"
	"sync"
	"testing"
	"time"
)

type testUsers struct{}

type userResolverFunc func(context.Context, string) (*User, error)

func (f userResolverFunc) ResolveUser(ctx context.Context, id string) (*User, error) {
	return f(ctx, id)
}

func (testUsers) ResolveUser(context.Context, string) (*User, error) {
	return &User{Subject: "u-1", Name: "Alice", PreferredUsername: "alice", Email: "alice@example.com", EmailVerified: true}, nil
}

type testSigner struct{}

type failingStore struct {
	Store
	operation string
	err       error
}

func (s failingStore) GetClient(ctx context.Context, id string) (*Client, error) {
	if s.operation == "client" {
		return nil, s.err
	}
	return s.Store.GetClient(ctx, id)
}
func (s failingStore) GetAuthorizationCode(ctx context.Context, hash string) (*AuthorizationCode, error) {
	if s.operation == "code" {
		return nil, s.err
	}
	return s.Store.GetAuthorizationCode(ctx, hash)
}
func (s failingStore) GetAccessToken(ctx context.Context, hash string) (*Token, error) {
	if s.operation == "corrupt-access" {
		return &Token{Hash: "wrong", UserID: "user", ClientID: "client", Scopes: []string{"openid"}, ExpiresAt: time.Unix(1_800_000_000, 0)}, nil
	}
	if s.operation == "access" {
		return nil, s.err
	}
	return s.Store.GetAccessToken(ctx, hash)
}
func (s failingStore) GetRefreshToken(ctx context.Context, hash string) (*Token, error) {
	if s.operation == "corrupt-refresh" {
		return &Token{Hash: hash, UserID: "user", ClientID: "client-1", Scopes: []string{"openid"}, ExpiresAt: time.Unix(1_800_000_000, 0)}, nil
	}
	return s.Store.GetRefreshToken(ctx, hash)
}
func (s failingStore) RevokeGrant(ctx context.Context, userID, clientID string, now time.Time) error {
	if s.operation == "revoke-grant" {
		return s.err
	}
	return s.Store.RevokeGrant(ctx, userID, clientID, now)
}

func testAuthentication() Authentication {
	return Authentication{UserID: "user-1", AuthTime: time.Unix(1_700_000_000, 0)}
}

func (testSigner) SignIDToken(_ context.Context, claims IDTokenClaims) (string, error) {
	if claims.Issuer != "https://forum.example.com/oauth2" || claims.Subject != "u-1" {
		return "", ErrInvalidRequest
	}
	if claims.AuthTime != int64(1_700_000_000) {
		return "", ErrInvalidRequest
	}
	return "signed-id-token", nil
}

func (testSigner) PublicKeys(context.Context) ([]JWK, error) {
	return []JWK{{KTY: "RSA", Use: "sig", Alg: "RS256", Kid: "test", N: "test", E: "AQAB"}}, nil
}

func testProvider(t testing.TB) (*Provider, *MemoryStore) {
	t.Helper()
	store := NewMemoryStore()
	store.PutClient(&Client{ID: "client-1", SecretHash: hash("secret"), RedirectURIs: []string{"https://app.example/callback"}, Scopes: []string{"openid", "profile", "email", "offline_access"}, GrantTypes: []string{"authorization_code", "refresh_token"}, TokenEndpointAuthMethod: ClientSecretPost, RequirePKCE: true, Public: false, Enabled: true})
	p, err := New(Config{Issuer: "https://forum.example.com/oauth2", Store: store, Users: testUsers{}, Signer: testSigner{}, Now: func() time.Time { return time.Unix(1_700_000_100, 0) }})
	if err != nil {
		t.Fatal(err)
	}
	return p, store
}

func TestAuthorizationCodePKCEAndSingleUse(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "authorization-code-verifier-with-43-characters-minimum"
	result, err := p.Authorize(ctx, AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, Nonce: "nonce", CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	_, err = p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: result.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: "not-the-verifier"})
	if err == nil {
		t.Fatal("expected PKCE failure")
	}
	request := TokenRequest{GrantType: "authorization_code", Code: result.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: verifier}
	tokens, err := p.ExchangeCode(ctx, request)
	if err != nil {
		t.Fatalf("valid exchange after failed PKCE: %v", err)
	}
	if _, err := p.ExchangeCode(ctx, request); err == nil {
		t.Fatal("expected authorization code reuse to fail")
	}
	if _, err := p.ValidateAccessToken(ctx, tokens.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("code replay did not revoke derived access token: %v", err)
	}
}

func TestRefreshRotationAndRevocation(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	// Use the S256 challenge generated by the helper below.
	verifier := "a-test-verifier-with-at-least-forty-three-characters"
	challenge := base64URLSHA256(verifier)
	code, err := p.Authorize(ctx, AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "email", "offline_access"}, Nonce: "nonce", CodeChallenge: challenge, CodeChallengeMethod: "S256", Prompt: []string{"consent"}}, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: verifier})
	if err != nil || tokens.RefreshToken == "" || tokens.AccessToken == "" {
		t.Fatalf("exchange failed: %v", err)
	}
	next, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if err != nil || next.RefreshToken == tokens.RefreshToken {
		t.Fatalf("refresh rotation failed: %v", err)
	}
	claims, err := p.UserInfo(ctx, next.AccessToken)
	if err != nil || claims.Subject != "u-1" || claims.Email != "alice@example.com" || claims.Name != "" {
		t.Fatalf("unexpected scoped userinfo: %+v, %v", claims, err)
	}
	if _, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost}); err == nil {
		t.Fatal("expected rotated token to be rejected")
	}
	if _, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: next.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost}); err == nil {
		t.Fatal("expected refresh family to be revoked after token reuse")
	}
	if err := p.Revoke(ctx, TokenRevocationRequest{Token: next.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, TokenTypeHint: "refresh_token"}); err != nil {
		t.Fatal(err)
	}
	if token, _ := store.GetRefreshToken(ctx, hash(next.RefreshToken)); token.RevokedAt == nil {
		t.Fatal("expected refresh token to be revoked")
	}
	storedRefresh, _ := store.GetRefreshToken(ctx, hash(next.RefreshToken))
	if err := p.RevokeRefreshTokenFamily(ctx, storedRefresh.FamilyID); err != nil {
		t.Fatal(err)
	}
	if _, err := p.ValidateAccessToken(ctx, next.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("family access token survived reuse: %v", err)
	}
}

func TestRevokeGrantRemovesConsentAndAllTokens(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	verifier := "revoke-grant-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", Prompt: []string{"consent"}}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	if err := p.RevokeGrant(ctx, "user-1", "client-1"); err != nil {
		t.Fatal(err)
	}
	if consent, _ := store.GetConsent(ctx, "user-1", "client-1"); consent != nil {
		t.Fatal("consent was not removed")
	}
	if _, err := p.ValidateAccessToken(ctx, tokens.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("access token remains valid: %v", err)
	}
	if _, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost}); err == nil {
		t.Fatal("refresh token remains valid")
	}
}

func TestRevokeGrantInvalidatesUnexchangedAuthorizationCodes(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "revoke-code-verifier-with-at-least-forty-three-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.RevokeGrant(ctx, "user-1", "client-1"); err != nil {
		t.Fatal(err)
	}
	_, err = p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("authorization code survived grant revocation: %v", err)
	}
}

func TestRevokingRefreshTokenRevokesFamilyAccessTokens(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "refresh-revocation-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, Prompt: []string{"consent"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Revoke(ctx, TokenRevocationRequest{Token: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, TokenTypeHint: "refresh_token"}); err != nil {
		t.Fatal(err)
	}
	if _, err := p.ValidateAccessToken(ctx, tokens.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("access token survived refresh revocation: %v", err)
	}
	if _, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost}); !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("refresh token survived revocation: %v", err)
	}
}

func TestNoRefreshTokenWithoutOfflineAccess(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "authorization-code-verifier-with-43-characters-minimum"
	code, err := p.Authorize(ctx, AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	if tokens.RefreshToken != "" {
		t.Fatal("refresh token issued without offline_access")
	}
}

func TestOfflineAccessRequiresExplicitConsentPrompt(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "offline-access-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	if tokens.RefreshToken != "" || contains(tokens.Scope, "offline_access") {
		t.Fatalf("offline access was granted without prompt=consent: %+v", tokens)
	}
}

func TestPromptNoneReturnsInteractionErrors(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "prompt-none-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", Prompt: []string{"none"}}
	if _, err := p.BeginAuthorization(ctx, req, Authentication{}); !errors.Is(err, ErrLoginRequired) {
		t.Fatalf("expected login_required: %v", err)
	}
	if _, err := p.BeginAuthorization(ctx, req, testAuthentication()); !errors.Is(err, ErrConsentRequired) {
		t.Fatalf("expected consent_required: %v", err)
	}
	req.Prompt = []string{"none", "consent"}
	if _, err := p.BeginAuthorization(ctx, req, testAuthentication()); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("invalid prompt combination accepted: %v", err)
	}
	req.Prompt = []string{"unknown"}
	if _, err := p.BeginAuthorization(ctx, req, testAuthentication()); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("unknown prompt accepted: %v", err)
	}
	req.Prompt = nil
	negative := -time.Second
	req.MaxAge = &negative
	if _, err := p.BeginAuthorization(ctx, req, testAuthentication()); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("negative max_age accepted: %v", err)
	}
}

func TestMaxAgeRequiresRecentAuthentication(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "max-age-verifier-with-at-least-forty-three-characters"
	maxAge := 30 * time.Second
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", MaxAge: &maxAge}
	decision, err := p.BeginAuthorization(ctx, req, testAuthentication())
	if err != nil || decision.Action != AuthorizationNeedLogin {
		t.Fatalf("stale authentication accepted: %+v, %v", decision, err)
	}
	auth := testAuthentication()
	auth.AuthTime = time.Unix(1_700_000_090, 0)
	auth.Fresh = true
	decision, err = p.BeginAuthorization(ctx, req, auth)
	if err != nil || decision.Action != AuthorizationNeedConsent {
		t.Fatalf("recent authentication rejected: %+v, %v", decision, err)
	}
}

func TestFutureAuthenticationTimeIsRejected(t *testing.T) {
	p, _ := testProvider(t)
	verifier := "future-auth-time-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	auth := testAuthentication()
	auth.AuthTime = time.Unix(1_700_000_101, 0)
	_, err := p.BeginAuthorization(context.Background(), req, auth)
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, ErrServer) {
		t.Fatalf("future authentication accepted: %#v", err)
	}
}

func TestUserUnavailableDiffersFromUserStoreFailure(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	verifier := "user-state-verifier-with-at-least-forty-three-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, Prompt: []string{"consent"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	newProvider := func(resolver UserResolver) *Provider {
		result, err := New(Config{Issuer: "https://forum.example.com/oauth2", Store: store, Users: resolver, Signer: testSigner{}, Now: func() time.Time { return time.Unix(1_700_000_100, 0) }})
		if err != nil {
			t.Fatal(err)
		}
		return result
	}
	storageFailure := errors.New("user database unavailable")
	broken := newProvider(userResolverFunc(func(context.Context, string) (*User, error) { return nil, storageFailure }))
	_, err = broken.UserInfo(ctx, tokens.AccessToken)
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, storageFailure) {
		t.Fatalf("user storage failure was misclassified: %#v", err)
	}
	unavailable := newProvider(userResolverFunc(func(context.Context, string) (*User, error) { return nil, ErrUserUnavailable }))
	_, err = unavailable.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("unavailable user refresh was not rejected: %v", err)
	}
	if _, err := unavailable.ValidateAccessToken(ctx, tokens.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("unavailable user family was not revoked: %v", err)
	}
}

func TestRefreshScopeCanOnlyNarrow(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "refresh-scope-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "profile", "offline_access"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", Prompt: []string{"consent"}}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	_, err = p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, Scope: []string{"openid", "email"}})
	if !errors.Is(err, ErrInvalidScope) {
		t.Fatalf("scope escalation was not rejected: %v", err)
	}
	_, err = p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, Scope: []string{"profile"}})
	if !errors.Is(err, ErrInvalidScope) {
		t.Fatalf("refresh scope without openid was accepted: %v", err)
	}
	narrowed, err := p.Refresh(ctx, TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, Scope: []string{"openid"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(narrowed.Scope) != 1 || narrowed.Scope[0] != "openid" {
		t.Fatalf("unexpected narrowed scopes: %v", narrowed.Scope)
	}
}

func TestMetadataIsStableAndHTTPAgnostic(t *testing.T) {
	p, _ := testProvider(t)
	metadata := p.Metadata()
	if metadata.Issuer != "https://forum.example.com/oauth2" || metadata.AuthorizationEndpoint != "https://forum.example.com/oauth2/authorize" {
		t.Fatalf("unexpected metadata endpoints: %+v", metadata)
	}
	if len(metadata.CodeChallengeMethodsSupported) != 1 || metadata.CodeChallengeMethodsSupported[0] != "S256" {
		t.Fatalf("unexpected PKCE metadata: %+v", metadata.CodeChallengeMethodsSupported)
	}
	if got := NewOAuthError("invalid_request", "bad request").Error(); got != "invalid_request: bad request" {
		t.Fatalf("unexpected oauth error: %s", got)
	}
}

func TestPublicJWKSUsesSignerKeyProvider(t *testing.T) {
	store := NewMemoryStore()
	keys, err := GenerateRSAKeySet("published", 2048)
	if err != nil {
		t.Fatal(err)
	}
	p, err := New(Config{Issuer: "https://issuer.example", Store: store, Users: testUsers{}, Signer: keys})
	if err != nil {
		t.Fatal(err)
	}
	jwks, err := p.PublicJWKS(context.Background())
	if err != nil || len(jwks.Keys) != 1 || jwks.Keys[0].Kid != "published" || jwks.Keys[0].Use != "sig" {
		t.Fatalf("unexpected provider JWKS: %+v, %v", jwks, err)
	}
	encoded, err := json.Marshal(jwks)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(encoded), `{"keys":[`) {
		t.Fatalf("invalid JWKS document shape: %s", encoded)
	}
}

func TestProviderScopesDriveValidationAndDiscovery(t *testing.T) {
	store := NewMemoryStore()
	store.PutClient(&Client{ID: "client", SecretHash: HashClientSecret("secret"), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid", "groups"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientSecretPost, Enabled: true})
	now := time.Unix(1_700_000_100, 0)
	p, err := New(Config{Issuer: "https://issuer.example", Store: store, Users: testUsers{}, Signer: testSigner{}, Now: func() time.Time { return now }, SupportedScopes: []string{"openid", "groups"}})
	if err != nil {
		t.Fatal(err)
	}
	if got := p.Metadata().ScopesSupported; len(got) != 2 || got[1] != "groups" {
		t.Fatalf("discovery scopes differ from policy: %v", got)
	}
	verifier := "provider-scope-verifier-with-at-least-43-characters"
	_, err = p.BeginAuthorization(context.Background(), AuthorizeRequest{ClientID: "client", RedirectURI: "https://client.example/callback", ResponseType: "code", Scope: []string{"openid", "email"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication())
	if !errors.Is(err, ErrInvalidScope) {
		t.Fatalf("unsupported provider scope accepted: %v", err)
	}
	if _, err := New(Config{Issuer: "https://issuer.example", Store: store, Users: testUsers{}, Signer: testSigner{}, SupportedScopes: []string{"profile"}}); err == nil {
		t.Fatal("provider scopes without openid accepted")
	}
}

func TestNewRejectsUnsafeIssuerAndAuthorizeRejectsUnsafeRedirect(t *testing.T) {
	_, store := testProvider(t)
	if _, err := New(Config{Issuer: "http://forum.example.com/oauth2", Store: store, Users: testUsers{}, Signer: testSigner{}}); err == nil {
		t.Fatal("insecure issuer accepted")
	}
	for _, issuer := range []string{"https://user@example.com/oauth2", "https://example.com/oauth2?", "https://example.com/oauth2#"} {
		if _, err := New(Config{Issuer: issuer, Store: store, Users: testUsers{}, Signer: testSigner{}}); err == nil {
			t.Fatalf("invalid issuer accepted: %s", issuer)
		}
	}
	if _, err := New(Config{Issuer: "http://localhost:5234/oauth2", AllowInsecureIssuer: true, Store: store, Users: testUsers{}, Signer: testSigner{}}); err != nil {
		t.Fatalf("explicit development issuer rejected: %v", err)
	}
	p, _ := testProvider(t)
	verifier := "unsafe-redirect-verifier-with-at-least-43-characters"
	_, err := p.Authorize(context.Background(), AuthorizeRequest{ClientID: "client-1", RedirectURI: "javascript:alert(1)", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("unsafe redirect was not rejected: %v", err)
	}
	client := Client{ID: "fragment", RedirectURIs: []string{"https://client.example/callback#"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientAuthNone, Public: true, Enabled: true}
	if err := ValidateClient(client); err == nil {
		t.Fatal("redirect URI with empty fragment accepted")
	}
}

func TestProtocolErrorPreservesStandardCodeAndCause(t *testing.T) {
	p, _ := testProvider(t)
	_, err := p.Authorize(context.Background(), AuthorizeRequest{ClientID: "missing"}, testAuthentication(), true)
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || protocolErr.Code != "unauthorized_client" {
		t.Fatalf("unexpected protocol error: %#v", err)
	}
	if !errors.Is(err, ErrInvalidClient) {
		t.Fatalf("expected invalid-client cause: %v", err)
	}
	if protocolErr.RedirectAllowed {
		t.Fatal("unknown client error must not be redirected")
	}

	verifier := "authorization-error-verifier-with-at-least-43-characters"
	_, err = p.Authorize(context.Background(), AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "forbidden"}, State: "opaque-state", CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if !errors.As(err, &protocolErr) || !protocolErr.RedirectAllowed || protocolErr.RedirectURI != "https://app.example/callback" || protocolErr.State != "opaque-state" {
		t.Fatalf("safe authorization error lacks redirect context: %#v", err)
	}

	_, err = p.Authorize(context.Background(), AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://attacker.example/callback", ResponseType: "invalid", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if !errors.As(err, &protocolErr) || protocolErr.RedirectAllowed {
		t.Fatalf("unregistered redirect was marked safe: %#v", err)
	}
}

func TestTokenEndpointAuthenticationMethodIsEnforced(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	verifier := "client-auth-method-verifier-with-at-least-43-characters"
	request := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, request, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	_, err = p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretBasic, RedirectURI: request.RedirectURI, CodeVerifier: verifier})
	if !errors.Is(err, ErrInvalidClient) {
		t.Fatalf("unregistered auth method accepted: %v", err)
	}

	store.PutClient(&Client{ID: "public-client", RedirectURIs: []string{"com.example.app:/callback"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientAuthNone, Public: true, Enabled: true})
	publicVerifier := "public-client-verifier-with-at-least-forty-three-characters"
	publicRequest := AuthorizeRequest{ClientID: "public-client", RedirectURI: "com.example.app:/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(publicVerifier), CodeChallengeMethod: "S256"}
	publicCode, err := p.Authorize(ctx, publicRequest, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: publicCode.Code, ClientID: "public-client", AuthMethod: ClientAuthNone, RedirectURI: publicRequest.RedirectURI, CodeVerifier: publicVerifier}); err != nil {
		t.Fatalf("public client authentication failed: %v", err)
	}
}

func TestConfidentialClientMayMakePKCEOptional(t *testing.T) {
	p, store := testProvider(t)
	store.PutClient(&Client{ID: "optional-pkce", SecretHash: HashClientSecret("secret"), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientSecretBasic, Enabled: true})
	req := AuthorizeRequest{ClientID: "optional-pkce", RedirectURI: "https://client.example/callback", ResponseType: "code", Scope: []string{"openid"}}
	code, err := p.Authorize(context.Background(), req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	_, err = p.ExchangeCode(context.Background(), TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "optional-pkce", ClientSecret: "secret", AuthMethod: ClientSecretBasic, RedirectURI: req.RedirectURI})
	if err != nil {
		t.Fatalf("optional PKCE confidential flow failed: %v", err)
	}
}

func TestClientRegistrationValidation(t *testing.T) {
	secret, err := GenerateClientSecret()
	if err != nil {
		t.Fatal(err)
	}
	client := Client{ID: "valid", SecretHash: HashClientSecret(secret), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid", "offline_access"}, GrantTypes: []string{"authorization_code", "refresh_token"}, TokenEndpointAuthMethod: ClientSecretBasic, Enabled: true}
	if err := ValidateClient(client); err != nil {
		t.Fatalf("valid client rejected: %v", err)
	}
	client.RedirectURIs = append(client.RedirectURIs, client.RedirectURIs[0])
	if err := ValidateClient(client); err == nil {
		t.Fatal("duplicate redirect URI accepted")
	}
	client.RedirectURIs = []string{"https://client.example/callback"}
	client.GrantTypes = []string{"authorization_code"}
	if err := ValidateClient(client); err == nil {
		t.Fatal("offline_access accepted without refresh grant")
	}
	client.GrantTypes = []string{"authorization_code", "refresh_token"}
	client.SecretHash = HashClientSecret("")
	if err := ValidateClient(client); err == nil {
		t.Fatal("empty client secret digest accepted")
	}
}

func TestMemoryStoreDoesNotExposeMutableState(t *testing.T) {
	store := NewMemoryStore()
	client := &Client{ID: "isolated", RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientAuthNone, Public: true, Enabled: true}
	store.PutClient(client)
	client.Scopes[0] = "mutated"
	loaded, err := store.GetClient(context.Background(), "isolated")
	if err != nil {
		t.Fatal(err)
	}
	loaded.Scopes[0] = "also-mutated"
	reloaded, _ := store.GetClient(context.Background(), "isolated")
	if reloaded.Scopes[0] != "openid" {
		t.Fatalf("store state escaped lock boundary: %v", reloaded.Scopes)
	}
}

func TestMemoryStorePurgeBoundsCredentialRetention(t *testing.T) {
	store := NewMemoryStore()
	ctx := context.Background()
	now := time.Unix(1_700_000_000, 0)
	verifier := "purge-store-verifier-with-at-least-forty-three-characters"
	used := &AuthorizationCode{Hash: "used", UserID: "user", ClientID: "client", RedirectURI: "https://client.example/callback", Scopes: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", ExpiresAt: now.Add(time.Minute)}
	expired := &AuthorizationCode{Hash: "expired", UserID: "user", ClientID: "client", RedirectURI: used.RedirectURI, Scopes: []string{"openid"}, CodeChallenge: used.CodeChallenge, CodeChallengeMethod: "S256", ExpiresAt: now}
	active := &AuthorizationCode{Hash: "active", UserID: "user", ClientID: "client", RedirectURI: used.RedirectURI, Scopes: []string{"openid"}, CodeChallenge: used.CodeChallenge, CodeChallengeMethod: "S256", ExpiresAt: now.Add(time.Hour)}
	for _, code := range []*AuthorizationCode{used, expired, active} {
		if err := store.SaveAuthorizationCode(ctx, code); err != nil {
			t.Fatal(err)
		}
	}
	access := &Token{Hash: "access", FamilyID: "family", UserID: "user", ClientID: "client", Scopes: []string{"openid"}, ExpiresAt: now.Add(time.Hour)}
	refresh := &Token{Hash: "refresh", FamilyID: "family", UserID: "user", ClientID: "client", Scopes: []string{"openid"}, ExpiresAt: now.Add(time.Hour), FamilyExpiresAt: now.Add(2 * time.Hour)}
	if err := store.ExchangeAuthorizationCode(ctx, AuthorizationCodeExchange{CodeHash: used.Hash, ClientID: used.ClientID, RedirectURI: used.RedirectURI, CodeVerifier: verifier, Now: now, AccessToken: access, RefreshToken: refresh}); err != nil {
		t.Fatal(err)
	}
	if err := store.RevokeToken(ctx, access.Hash, "client", now); err != nil {
		t.Fatal(err)
	}
	result, err := store.Purge(ctx, PurgeRequest{Now: now, RevokedBefore: now.Add(-time.Hour)})
	if err != nil {
		t.Fatal(err)
	}
	if result.AuthorizationCodes != 2 || result.AccessTokens != 0 || result.RefreshTokens != 0 {
		t.Fatalf("unexpected initial purge: %+v", result)
	}
	if code, _ := store.GetAuthorizationCode(ctx, active.Hash); code == nil {
		t.Fatal("active code was purged")
	}
	result, err = store.Purge(ctx, PurgeRequest{Now: now.Add(time.Hour), RevokedBefore: now})
	if err != nil {
		t.Fatal(err)
	}
	if result.AuthorizationCodes != 1 || result.AccessTokens != 1 || result.RefreshTokens != 1 {
		t.Fatalf("terminal credentials retained: %+v", result)
	}
}

func TestAuthorizationRejectsMalformedOrDuplicateScopes(t *testing.T) {
	p, _ := testProvider(t)
	verifier := "invalid-scope-verifier-with-at-least-43-characters"
	base := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	for _, scopes := range [][]string{{"openid", "openid"}, {"openid", "bad scope"}, {"openid", "bad\"scope"}} {
		base.Scope = scopes
		if _, err := p.Authorize(context.Background(), base, testAuthentication(), true); !errors.Is(err, ErrInvalidScope) {
			t.Fatalf("invalid scopes accepted %q: %v", scopes, err)
		}
	}
}

func TestSubjectIdentifierValidation(t *testing.T) {
	for _, subject := range []string{"", "contains\nnewline", "用户", strings.Repeat("a", 256)} {
		if validSubject(subject) {
			t.Fatalf("invalid subject accepted: %q", subject)
		}
	}
	if !validSubject("user-123_ABC") {
		t.Fatal("valid subject rejected")
	}
}

func TestAuthorizationResponseModeIsValidatedAndNormalized(t *testing.T) {
	p, _ := testProvider(t)
	verifier := "response-mode-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, State: "state", CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	result, err := p.Authorize(context.Background(), req, testAuthentication(), true)
	if err != nil || result.ResponseMode != "query" {
		t.Fatalf("default response mode not normalized: %+v, %v", result, err)
	}
	req.ResponseMode = "fragment"
	_, err = p.BeginAuthorization(context.Background(), req, testAuthentication())
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || !errors.Is(err, ErrUnsupportedResponseMode) || protocolErr.Code != "unsupported_response_mode" || protocolErr.ResponseMode != "query" {
		t.Fatalf("unsupported mode error is incomplete: %#v", err)
	}
}

func TestEntropyFailureReturnsServerErrorWithoutAuthorizationCode(t *testing.T) {
	store := NewMemoryStore()
	store.PutClient(&Client{ID: "client", SecretHash: HashClientSecret("secret"), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientSecretPost, Enabled: true})
	p, err := New(Config{Issuer: "https://issuer.example", Store: store, Users: testUsers{}, Signer: testSigner{}, Random: bytes.NewReader(nil), Now: func() time.Time { return time.Unix(1_700_000_100, 0) }})
	if err != nil {
		t.Fatal(err)
	}
	verifier := "entropy-failure-verifier-with-at-least-43-characters"
	_, err = p.Authorize(context.Background(), AuthorizeRequest{ClientID: "client", RedirectURI: "https://client.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, ErrServer) {
		t.Fatalf("unexpected entropy error: %#v", err)
	}
}

func TestStoreFailuresAreReportedAsServerErrors(t *testing.T) {
	_, store := testProvider(t)
	storeFailure := errors.New("database unavailable")
	newProvider := func(operation string) *Provider {
		p, err := New(Config{Issuer: "https://forum.example.com/oauth2", Store: failingStore{Store: store, operation: operation, err: storeFailure}, Users: testUsers{}, Signer: testSigner{}, Now: func() time.Time { return time.Unix(1_700_000_100, 0) }})
		if err != nil {
			t.Fatal(err)
		}
		return p
	}
	verifier := "store-failure-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	_, err := newProvider("client").BeginAuthorization(context.Background(), req, testAuthentication())
	var protocolErr *OAuthError
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, storeFailure) || !errors.Is(err, ErrServer) {
		t.Fatalf("client store failure was masked: %#v", err)
	}
	_, err = newProvider("access").ValidateAccessToken(context.Background(), "opaque-token")
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, storeFailure) {
		t.Fatalf("access store failure was masked: %#v", err)
	}
	err = newProvider("revoke-grant").RevokeGrant(context.Background(), "user-1", "client-1")
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" || !errors.Is(err, storeFailure) {
		t.Fatalf("grant revocation failure was masked: %#v", err)
	}
	_, err = newProvider("corrupt-access").ValidateAccessToken(context.Background(), "opaque-token")
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" {
		t.Fatalf("corrupt access token was accepted: %#v", err)
	}
	_, err = newProvider("corrupt-refresh").Refresh(context.Background(), TokenRequest{GrantType: "refresh_token", RefreshToken: "opaque-refresh", ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if !errors.As(err, &protocolErr) || protocolErr.Code != "server_error" {
		t.Fatalf("corrupt refresh token was accepted: %#v", err)
	}
}

func TestCredentialExpirationIsExclusiveAtBoundary(t *testing.T) {
	store := NewMemoryStore()
	store.PutClient(&Client{ID: "client", SecretHash: HashClientSecret("secret"), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid", "offline_access"}, GrantTypes: []string{"authorization_code", "refresh_token"}, TokenEndpointAuthMethod: ClientSecretPost, Enabled: true})
	clock := time.Unix(1_700_000_100, 0)
	p, err := New(Config{Issuer: "https://forum.example.com/oauth2", AuthorizationCodeTTL: time.Minute, AccessTokenTTL: 2 * time.Minute, RefreshTokenTTL: 3 * time.Minute, Store: store, Users: testUsers{}, Signer: testSigner{}, Now: func() time.Time { return clock }})
	if err != nil {
		t.Fatal(err)
	}
	auth := testAuthentication()
	verifier := "expiration-boundary-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client", RedirectURI: "https://client.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, Prompt: []string{"consent"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}

	code, err := p.Authorize(context.Background(), req, auth, true)
	if err != nil {
		t.Fatal(err)
	}
	clock = clock.Add(time.Minute)
	_, err = p.ExchangeCode(context.Background(), TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("authorization code valid at expiry boundary: %v", err)
	}

	clock = time.Unix(1_700_000_100, 0)
	code, err = p.Authorize(context.Background(), req, auth, true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(context.Background(), TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	clock = clock.Add(2 * time.Minute)
	if _, err := p.ValidateAccessToken(context.Background(), tokens.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("access token valid at expiry boundary: %v", err)
	}
	clock = clock.Add(time.Minute)
	_, err = p.Refresh(context.Background(), TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("refresh token valid at expiry boundary: %v", err)
	}
}

func TestRefreshRotationCannotExtendFamilyLifetime(t *testing.T) {
	store := NewMemoryStore()
	store.PutClient(&Client{ID: "client", SecretHash: HashClientSecret("secret"), RedirectURIs: []string{"https://client.example/callback"}, Scopes: []string{"openid", "offline_access"}, GrantTypes: []string{"authorization_code", "refresh_token"}, TokenEndpointAuthMethod: ClientSecretPost, Enabled: true})
	clock := time.Unix(1_700_000_100, 0)
	p, err := New(Config{Issuer: "https://forum.example.com/oauth2", RefreshTokenTTL: time.Hour, RefreshTokenMaxLifetime: 90 * time.Minute, Store: store, Users: testUsers{}, Signer: testSigner{}, Now: func() time.Time { return clock }})
	if err != nil {
		t.Fatal(err)
	}
	verifier := "family-lifetime-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client", RedirectURI: "https://client.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, Prompt: []string{"consent"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(context.Background(), req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	tokens, err := p.ExchangeCode(context.Background(), TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	initial, _ := store.GetRefreshToken(context.Background(), hash(tokens.RefreshToken))
	clock = clock.Add(59 * time.Minute)
	rotated, err := p.Refresh(context.Background(), TokenRequest{GrantType: "refresh_token", RefreshToken: tokens.RefreshToken, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if err != nil {
		t.Fatal(err)
	}
	stored, _ := store.GetRefreshToken(context.Background(), hash(rotated.RefreshToken))
	if !stored.ExpiresAt.Equal(initial.FamilyExpiresAt) || !stored.FamilyExpiresAt.Equal(initial.FamilyExpiresAt) {
		t.Fatalf("rotation extended family lifetime: initial=%v rotated=%v family=%v", initial.FamilyExpiresAt, stored.ExpiresAt, stored.FamilyExpiresAt)
	}
	clock = initial.FamilyExpiresAt
	_, err = p.Refresh(context.Background(), TokenRequest{GrantType: "refresh_token", RefreshToken: rotated.RefreshToken, ClientID: "client", ClientSecret: "secret", AuthMethod: ClientSecretPost})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("family valid at absolute expiry: %v", err)
	}
}

func TestBeginAuthorizationReportsLoginConsentAndReady(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "authorization-decision-verifier-with-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "profile"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	decision, err := p.BeginAuthorization(ctx, req, Authentication{})
	if err != nil || decision.Action != AuthorizationNeedLogin {
		t.Fatalf("expected login decision: %+v, %v", decision, err)
	}
	if decision.Client.ID != "client-1" || decision.Client.Name != "" || decision.Client.Public {
		t.Fatalf("unexpected authorization client view: %+v", decision.Client)
	}
	decision, err = p.BeginAuthorization(ctx, req, testAuthentication())
	if err != nil || decision.Action != AuthorizationNeedConsent {
		t.Fatalf("expected consent decision: %+v, %v", decision, err)
	}
	if _, err := p.Authorize(ctx, req, testAuthentication(), true); err != nil {
		t.Fatal(err)
	}
	decision, err = p.BeginAuthorization(ctx, req, testAuthentication())
	if err != nil || decision.Action != AuthorizationReady {
		t.Fatalf("expected ready decision: %+v, %v", decision, err)
	}
}

func TestRepeatedConsentMergesScopes(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	verifier := "merged-consent-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "profile"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	if _, err := p.Authorize(ctx, req, testAuthentication(), true); err != nil {
		t.Fatal(err)
	}
	req.Scope = []string{"openid", "email"}
	if _, err := p.Authorize(ctx, req, testAuthentication(), true); err != nil {
		t.Fatal(err)
	}
	consent, err := store.GetConsent(ctx, "user-1", "client-1")
	if err != nil {
		t.Fatal(err)
	}
	if !contains(consent.Scopes, "profile") || !contains(consent.Scopes, "email") {
		t.Fatalf("consent scopes were narrowed: %v", consent.Scopes)
	}
}

func TestAuthorizationCodeConcurrentExchangeHasOneWinner(t *testing.T) {
	p, _ := testProvider(t)
	ctx := context.Background()
	verifier := "concurrent-authorization-code-verifier-43-characters"
	code, err := p.Authorize(ctx, AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	request := TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: verifier}
	const workers = 16
	var wg sync.WaitGroup
	type exchangeResult struct {
		tokens *TokenResponse
		err    error
	}
	results := make(chan exchangeResult, workers)
	for range workers {
		wg.Add(1)
		go func() {
			defer wg.Done()
			tokens, err := p.ExchangeCode(ctx, request)
			results <- exchangeResult{tokens: tokens, err: err}
		}()
	}
	wg.Wait()
	close(results)
	winners := 0
	var winner *TokenResponse
	for result := range results {
		if result.err == nil {
			winners++
			winner = result.tokens
		}
	}
	if winners != 1 {
		t.Fatalf("authorization code had %d successful consumers", winners)
	}
	if _, err := p.ValidateAccessToken(ctx, winner.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("concurrent code replay did not revoke winner token: %v", err)
	}
}

func TestAuthorizationCodeIsBoundToClient(t *testing.T) {
	p, store := testProvider(t)
	store.PutClient(&Client{ID: "other-client", SecretHash: HashClientSecret("other-secret"), RedirectURIs: []string{"https://app.example/callback"}, Scopes: []string{"openid"}, GrantTypes: []string{"authorization_code"}, TokenEndpointAuthMethod: ClientSecretBasic, Enabled: true})
	ctx := context.Background()
	verifier := "client-bound-code-verifier-with-at-least-43-characters"
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256"}
	code, err := p.Authorize(ctx, req, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	_, err = p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "other-client", ClientSecret: "other-secret", AuthMethod: ClientSecretBasic, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if !errors.Is(err, ErrInvalidGrant) {
		t.Fatalf("authorization code accepted for another client: %v", err)
	}
	_, err = p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: req.RedirectURI, CodeVerifier: verifier})
	if err != nil {
		t.Fatalf("wrong client consumed authorization code: %v", err)
	}
}

func TestConcurrentRefreshReuseRevokesWinningFamily(t *testing.T) {
	p, store := testProvider(t)
	ctx := context.Background()
	verifier := "concurrent-refresh-token-verifier-43-characters-long"
	code, err := p.Authorize(ctx, AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid", "offline_access"}, CodeChallenge: base64URLSHA256(verifier), CodeChallengeMethod: "S256", Prompt: []string{"consent"}}, testAuthentication(), true)
	if err != nil {
		t.Fatal(err)
	}
	issued, err := p.ExchangeCode(ctx, TokenRequest{GrantType: "authorization_code", Code: code.Code, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost, RedirectURI: "https://app.example/callback", CodeVerifier: verifier})
	if err != nil {
		t.Fatal(err)
	}
	request := TokenRequest{GrantType: "refresh_token", RefreshToken: issued.RefreshToken, ClientID: "client-1", ClientSecret: "secret", AuthMethod: ClientSecretPost}
	results := make(chan *TokenResponse, 2)
	var wg sync.WaitGroup
	for range 2 {
		wg.Add(1)
		go func() { defer wg.Done(); result, _ := p.Refresh(ctx, request); results <- result }()
	}
	wg.Wait()
	close(results)
	var winner *TokenResponse
	for result := range results {
		if result != nil {
			if winner != nil {
				t.Fatal("refresh token had multiple winners")
			}
			winner = result
		}
	}
	if winner == nil {
		t.Fatal("refresh token had no winner")
	}
	stored, _ := store.GetRefreshToken(ctx, hash(winner.RefreshToken))
	if stored == nil || stored.RevokedAt == nil {
		t.Fatal("reuse did not revoke the winning token family")
	}
	if _, err := p.ValidateAccessToken(ctx, winner.AccessToken); !errors.Is(err, ErrTokenRevoked) {
		t.Fatalf("reuse did not revoke family access token: %v", err)
	}
}

func base64URLSHA256(value string) string {
	sum := sha256.Sum256([]byte(value))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

func TestMaxAgeRequiresVerifiedAuthenticationEvenForRecentSession(t *testing.T) {
	p, _ := testProvider(t)
	maxAge := time.Second
	req := AuthorizeRequest{ClientID: "client-1", RedirectURI: "https://app.example/callback", ResponseType: "code", Scope: []string{"openid"}, CodeChallenge: base64URLSHA256("max-age-verifier-with-at-least-forty-three-characters"), CodeChallengeMethod: "S256", MaxAge: &maxAge}
	auth := Authentication{UserID: "user-1", AuthTime: p.cfg.Now()}
	decision, err := p.BeginAuthorization(t.Context(), req, auth)
	if err != nil || decision.Action != AuthorizationNeedLogin {
		t.Fatalf("unverified session accepted: %+v %v", decision, err)
	}
	if _, err := p.Authorize(t.Context(), req, auth, true); err == nil {
		t.Fatal("unverified session issued authorization code")
	}
	auth.AuthID = "password-authentication"
	decision, err = p.BeginAuthorization(t.Context(), req, auth)
	if err != nil || decision.Action != AuthorizationNeedConsent {
		t.Fatalf("verified recent session rejected: %+v %v", decision, err)
	}
	auth.AuthID = ""
	req.MaxAge = nil
	decision, err = p.BeginAuthorization(t.Context(), req, auth)
	if err != nil || decision.Action != AuthorizationNeedConsent {
		t.Fatalf("ordinary federated login rejected: %+v %v", decision, err)
	}
}
