import { preparedPage, prepareGoosePage } from '@gooseforum/runtime/prepared-page'
import { normalizeAdminPath } from './navigation'

const loadDashboardPage = () => import('./pages/dashboard-page')
const loadCategoriesPage = () => import('./pages/categories-management-page').then((module) => ({ default: module.CategoriesManagementPage }))
const loadAccessGroupsPage = () => import('./pages/access-groups-management-page').then((module) => ({ default: module.AccessGroupsManagementPage }))
const loadRolesPage = () => import('./pages/roles-management-page').then((module) => ({ default: module.RolesManagementPage }))
const loadUsersPage = () => import('./pages/users-management-page').then((module) => ({ default: module.UsersManagementPage }))
const loadPostsPage = () => import('./pages/posts-management-page').then((module) => ({ default: module.PostsManagementPage }))
const loadLinksPage = () => import('./pages/links-management-page').then((module) => ({ default: module.LinksManagementPage }))
const loadSponsorsPage = () => import('./pages/sponsors-management-page').then((module) => ({ default: module.SponsorsManagementPage }))
const loadBadgesPage = () => import('./pages/badges-management-page').then((module) => ({ default: module.BadgesManagementPage }))
const loadFilesPage = () => import('./pages/file-resources-management-page').then((module) => ({ default: module.FileResourcesManagementPage }))
const loadAuditPage = () => import('./pages/opt-records-management-page').then((module) => ({ default: module.OptRecordsManagementPage }))
const loadSiteInfoPage = () => import('./pages/site-info-management-page').then((module) => ({ default: module.SiteInfoManagementPage }))
const loadSiteChromePage = () => import('./pages/site-chrome-management-page').then((module) => ({ default: module.SiteChromeManagementPage }))
const loadMailPage = () => import('./pages/mail-settings-page').then((module) => ({ default: module.MailSettingsPage }))
const loadSecurityPage = () => import('./pages/security-settings-page').then((module) => ({ default: module.SecuritySettingsPage }))
const loadPostingPage = () => import('./pages/posting-settings-page').then((module) => ({ default: module.PostingSettingsPage }))
const loadAnnouncementPage = () => import('./pages/announcement-settings-page').then((module) => ({ default: module.AnnouncementSettingsPage }))
const loadHttpNotifyPage = () => import('./pages/http-notify-settings-page').then((module) => ({ default: module.HttpNotifySettingsPage }))
const loadSensitiveWordsPage = () => import('./pages/sensitive-words-settings-page').then((module) => ({ default: module.SensitiveWordsSettingsPage }))
const loadOAuthPage = () => import('./pages/oauth-settings-page').then((module) => ({ default: module.OAuthSettingsPage }))
const loadOIDCProviderPage = () => import('./pages/oidc-provider-settings-page').then((module) => ({ default: module.OIDCProviderSettingsPage }))
export const DashboardPage = preparedPage('admin:/admin', loadDashboardPage)
export const CategoriesManagementPage = preparedPage('admin:/admin/categories', loadCategoriesPage)
export const AccessGroupsManagementPage = preparedPage('admin:/admin/access-groups', loadAccessGroupsPage)
export const RolesManagementPage = preparedPage('admin:/admin/roles', loadRolesPage)
export const UsersManagementPage = preparedPage('admin:/admin/users', loadUsersPage)
export const PostsManagementPage = preparedPage('admin:/admin/posts', loadPostsPage)
export const LinksManagementPage = preparedPage('admin:/admin/links', loadLinksPage)
export const SponsorsManagementPage = preparedPage('admin:/admin/sponsors', loadSponsorsPage)
export const BadgesManagementPage = preparedPage('admin:/admin/badges', loadBadgesPage)
export const FileResourcesManagementPage = preparedPage('admin:/admin/files/resources', loadFilesPage)
export const OptRecordsManagementPage = preparedPage('admin:/admin/opt-records', loadAuditPage)
export const SiteInfoManagementPage = preparedPage('admin:/admin/settings/site-info', loadSiteInfoPage)
export const SiteChromeManagementPage = preparedPage('admin:/admin/settings/site-chrome', loadSiteChromePage)
export const MailSettingsPage = preparedPage('admin:/admin/settings/mail', loadMailPage)
export const SecuritySettingsPage = preparedPage('admin:/admin/settings/security', loadSecurityPage)
export const PostingSettingsPage = preparedPage('admin:/admin/settings/posting', loadPostingPage)
export const AnnouncementSettingsPage = preparedPage('admin:/admin/settings/announcement', loadAnnouncementPage)
export const HttpNotifySettingsPage = preparedPage('admin:/admin/settings/http-notify', loadHttpNotifyPage)
export const SensitiveWordsSettingsPage = preparedPage('admin:/admin/settings/sensitive-words', loadSensitiveWordsPage)
export const OAuthSettingsPage = preparedPage('admin:/admin/settings/oauth', loadOAuthPage)
export const OIDCProviderSettingsPage = preparedPage('admin:/admin/settings/oidc-provider', loadOIDCProviderPage)

export function prepareAdminPage(path: string) {
  return prepareGoosePage('admin:' + normalizeAdminPath(path))
}
