/**
 * Public site API routes consumed by alternative themes. The Go route contract
 * test reads this catalog, so server and SDK routing cannot drift silently.
 */
export const siteApiRoutes = {
  accessGroupsList: ['GET', '/api/forum/access-groups'],
  accessGroupsApply: ['POST', '/api/forum/access-groups/apply'],
  accessGroupsManaged: ['GET', '/api/forum/access-groups/managed'],
  accessGroupsReview: ['POST', '/api/forum/access-groups/managed/review'],
  postsCreate: ['POST', '/api/forum/posts/create'],
  postsUpdate: ['POST', '/api/forum/posts/update'],
  postsDelete: ['POST', '/api/forum/posts/delete'],
  postsWindow: ['GET', '/api/forum/posts/window'],
  topicsLike: ['POST', '/api/forum/topics/like'],
  topicsBookmark: ['POST', '/api/forum/topics/bookmark'],
  topicsWatch: ['POST', '/api/forum/topics/watch'],
  topicsStatus: ['POST', '/api/forum/topics/status'],
  topicsWrite: ['POST', '/api/forum/topics/write'],
  moderationTopicStatus: ['POST', '/api/forum/moderation/topic-status'],
  moderationPostStatus: ['POST', '/api/forum/moderation/post-status'],
  moderationReport: ['POST', '/api/forum/report'],
  moderationReports: ['POST', '/api/forum/moderation/reports'],
  moderationReportStatus: ['POST', '/api/forum/moderation/report-status'],
  moderationLogs: ['POST', '/api/forum/moderation/logs'],
  notificationsList: ['GET', '/api/forum/notifications'],
  notificationsMarkRead: ['POST', '/api/forum/notification/mark-read'],
  notificationsMarkAllRead: ['POST', '/api/forum/notification/mark-all-read'],
  notificationsUnread: ['GET', '/api/forum/unread-status'],
  userCard: ['GET', '/api/user-card'],
  userFollow: ['POST', '/api/forum/follow-user'],
  userSaveInfo: ['POST', '/api/set-user-info'],
  userSaveCover: ['POST', '/api/set-user-profile-cover'],
  userSavePresetAvatar: ['POST', '/api/set-preset-avatar'],
  userWearBadge: ['POST', '/api/wear-badge'],
  userSaveEmail: ['POST', '/api/set-user-email'],
  userResendActivationEmail: ['POST', '/api/resend-activation-email'],
  userSaveUsername: ['POST', '/api/set-user-name'],
  userChangePassword: ['POST', '/api/change-password'],
  userOauthBindings: ['GET', '/api/oauth/bindings'],
  userUnbindOauth: ['POST', '/api/auth/:provider/unbind'],
  chatMessages: ['POST', '/api/forum/chat/messages'],
  chatSend: ['POST', '/api/forum/chat/send'],
  chatMarkRead: ['POST', '/api/forum/chat/mark-read'],
  authCaptcha: ['GET', '/api/get-captcha'],
  authLoginPublicKey: ['GET', '/api/login-public-key'],
  authLogin: ['POST', '/api/login'],
  authRegister: ['POST', '/api/register'],
  authForgotPassword: ['POST', '/api/forgot-password'],
  authResetPassword: ['POST', '/api/reset-password'],
  authLogout: ['POST', '/api/logout'],
  themeSave: ['POST', '/api/admin/save-site-theme'],
  themePublish: ['POST', '/api/admin/publish-site-theme'],
  imageUpload: ['POST', '/file/img-upload'],
  imageUploadInit: ['POST', '/file/img-upload/init'],
  imageUploadComplete: ['POST', '/file/img-upload/complete'],
  imageUploadAbort: ['POST', '/file/img-upload/abort'],
  avatarUpload: ['POST', '/api/upload-avatar'],
} as const satisfies Record<string, readonly ['GET' | 'POST', string]>
