[app]
name = "app"
env = "production" # APP_ENV in local,production
debug = false
maintenance = false

[server]
url = "http://localhost"
port = 99

[footer]
url = "https://github.com/leanCodeBox/GooseForum"
text = "Powered by GooseForum"

[jwtopt]
signingKey="{{.SigningKey}}"
validTime = 604800

[mail]
host = "smtp.example.com"
port = 587
username = "noreply@example.com"
password = "your-password"
from_name = "GooseForum"

[db]
migration = "on" # on,off
backupSqlite = true
backupDir = "./storage/databasebackup/"
keep = 7
spec = "0 3 * * *"

[db.default]
connection = "sqlite"# in mysql sqlite
url = "db_user:db_pass@tcp(db_host:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local"
path = "./storage/database/sqlite.db"# :memory:|./storage/database/sqlite.db

maxIdleConnections = 3
maxOpenConnections = 5
maxLifeSeconds = 300

[db.file]
connection = "sqlite"# in mysql sqlite
url = "root:root_password@tcp(127.0.0.1:3306)/goose_forum?charset=utf8mb4&parseTime=True&loc=Local"
path = "./storage/database/file.db"# :memory:|./storage/database/sqlite.db

maxIdleConnections = 3
maxOpenConnections = 5
maxLifeSeconds = 300

[meilisearch]
url = "http://localhost:7700"
masterkey=""

[log]
type = "file"# LOG_TYPE stdout,file
path = "./storage/logs/run.log"
rolling = true # 是否开启滚动 true ,false
maxage = 10 # 最大日期
maxsize = 256 # 最大文件大小 MB
maxBackUps = 30 # 最大保留文件数量

