import type { SiteTheme } from '@/runtime/site-theme'
import type { SiteThemeTokenKey } from '@/types/payload'

export type SiteThemePreset = {
  key: string
  swatches: string[]
  themes: Record<SiteTheme, Partial<Record<SiteThemeTokenKey, string>>>
}

export const themePresets: SiteThemePreset[] = [
  {
    key: 'goose',
    swatches: ['#ffffff', '#315ef4', '#10b981', '#1b1b1b'],
    themes: {
      'gf-light': {
        'color-base-100': '#ffffff',
        'color-base-200': '#f8fafc',
        'color-base-300': '#f1f5f9',
        'color-base-content': '#111827',
        'color-icon-muted': '#64748b',
        'color-line': '#e2e8f0',
        'color-primary': '#315ef4',
        'color-primary-content': '#ffffff',
        'color-secondary': '#f0f4f8',
        'color-secondary-content': '#1f2937',
        'color-accent': '#10b981',
        'color-accent-content': '#052e2b',
        'color-neutral': '#1f2937',
        'color-neutral-content': '#ffffff',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#16a34a',
        'color-success-content': '#f0fdf4',
        'color-warning': '#f59e0b',
        'color-warning-content': '#fffbeb',
        'color-error': '#dc2626',
        'color-error-content': '#fef2f2',
      },
      'gf-dark': {
        'color-base-100': '#1b1b1b',
        'color-base-200': '#111111',
        'color-base-300': '#2b2b2b',
        'color-base-content': '#eeeeee',
        'color-icon-muted': '#b5b5b5',
        'color-line': '#3d3d3d',
        'color-primary': '#68a1ff',
        'color-primary-content': '#111111',
        'color-secondary': '#2b2b2b',
        'color-secondary-content': '#eeeeee',
        'color-accent': '#31d97b',
        'color-accent-content': '#111111',
        'color-neutral': '#eeeeee',
        'color-neutral-content': '#111111',
        'color-info': '#6fb7ff',
        'color-info-content': '#111111',
        'color-success': '#3ee7a7',
        'color-success-content': '#111111',
        'color-warning': '#ffd166',
        'color-warning-content': '#111111',
        'color-error': '#ff7a8a',
        'color-error-content': '#111111',
      },
    },
  },
  {
    key: 'clean',
    swatches: ['#fbfdff', '#2563eb', '#14b8a6', '#101418'],
    themes: {
      'gf-light': {
        'color-base-100': '#fbfdff',
        'color-base-200': '#f3f6fa',
        'color-base-300': '#e8eef5',
        'color-base-content': '#172033',
        'color-icon-muted': '#6b778a',
        'color-line': '#d9e1ec',
        'color-primary': '#2563eb',
        'color-primary-content': '#ffffff',
        'color-secondary': '#e8eef5',
        'color-secondary-content': '#1e293b',
        'color-accent': '#14b8a6',
        'color-accent-content': '#042f2e',
        'color-neutral': '#1e293b',
        'color-neutral-content': '#ffffff',
        'color-info': '#0284c7',
        'color-info-content': '#eff6ff',
        'color-success': '#059669',
        'color-success-content': '#ecfdf5',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#e11d48',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#101418',
        'color-base-200': '#0b0f13',
        'color-base-300': '#1a2028',
        'color-base-content': '#f4f7fb',
        'color-icon-muted': '#9aa8b8',
        'color-line': '#2a3440',
        'color-primary': '#60a5fa',
        'color-primary-content': '#07111f',
        'color-secondary': '#1f2937',
        'color-secondary-content': '#e5edf6',
        'color-accent': '#2dd4bf',
        'color-accent-content': '#031f1d',
        'color-neutral': '#e5edf6',
        'color-neutral-content': '#0b0f13',
        'color-info': '#38bdf8',
        'color-info-content': '#07111f',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'warm',
    swatches: ['#fffaf4', '#b45309', '#0f766e', '#15110d'],
    themes: {
      'gf-light': {
        'color-base-100': '#fffaf4',
        'color-base-200': '#f7efe3',
        'color-base-300': '#eadfce',
        'color-base-content': '#2a2118',
        'color-icon-muted': '#8a7662',
        'color-line': '#dfd1bf',
        'color-primary': '#b45309',
        'color-primary-content': '#fff7ed',
        'color-secondary': '#f1e4d3',
        'color-secondary-content': '#3b2f23',
        'color-accent': '#0f766e',
        'color-accent-content': '#ecfeff',
        'color-neutral': '#3b2f23',
        'color-neutral-content': '#fffaf4',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#15803d',
        'color-success-content': '#f0fdf4',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#be123c',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#15110d',
        'color-base-200': '#0f0c09',
        'color-base-300': '#241c15',
        'color-base-content': '#f7efe6',
        'color-icon-muted': '#b8a895',
        'color-line': '#3a2e22',
        'color-primary': '#f59e0b',
        'color-primary-content': '#1f1300',
        'color-secondary': '#2b2118',
        'color-secondary-content': '#f7efe6',
        'color-accent': '#2dd4bf',
        'color-accent-content': '#031f1d',
        'color-neutral': '#f7efe6',
        'color-neutral-content': '#15110d',
        'color-info': '#60a5fa',
        'color-info-content': '#061224',
        'color-success': '#4ade80',
        'color-success-content': '#061a0f',
        'color-warning': '#facc15',
        'color-warning-content': '#211a00',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'deep',
    swatches: ['#f7f8fa', '#4f46e5', '#06b6d4', '#080808'],
    themes: {
      'gf-light': {
        'color-base-100': '#f7f8fa',
        'color-base-200': '#eef1f5',
        'color-base-300': '#dfe5ee',
        'color-base-content': '#101218',
        'color-icon-muted': '#667085',
        'color-line': '#d6dde8',
        'color-primary': '#4f46e5',
        'color-primary-content': '#ffffff',
        'color-secondary': '#e8ebf3',
        'color-secondary-content': '#111827',
        'color-accent': '#06b6d4',
        'color-accent-content': '#06242a',
        'color-neutral': '#111827',
        'color-neutral-content': '#ffffff',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#16a34a',
        'color-success-content': '#f0fdf4',
        'color-warning': '#eab308',
        'color-warning-content': '#1f1600',
        'color-error': '#e11d48',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#080808',
        'color-base-200': '#050505',
        'color-base-300': '#171717',
        'color-base-content': '#f5f5f5',
        'color-icon-muted': '#a3a3a3',
        'color-line': '#2a2a2a',
        'color-primary': '#818cf8',
        'color-primary-content': '#080808',
        'color-secondary': '#191919',
        'color-secondary-content': '#f5f5f5',
        'color-accent': '#22d3ee',
        'color-accent-content': '#071216',
        'color-neutral': '#f5f5f5',
        'color-neutral-content': '#080808',
        'color-info': '#60a5fa',
        'color-info-content': '#07111f',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
].map((preset) => ({
  ...preset,
  themes: {
    'gf-light': {
      ...preset.themes['gf-light'],
      'radius-selector': '0.5rem',
      'radius-field': '0.5rem',
      'radius-box': '0.5rem',
      'size-selector': '0.25rem',
      'size-field': '0.25rem',
      border: '1px',
      depth: '1',
      noise: '0',
    },
    'gf-dark': {
      ...preset.themes['gf-dark'],
      'radius-selector': '0.5rem',
      'radius-field': '0.5rem',
      'radius-box': '0.5rem',
      'size-selector': '0.25rem',
      'size-field': '0.25rem',
      border: '1px',
      depth: '1',
      noise: '0',
    },
  },
}))
