import type { SiteTheme } from '@/runtime/site-theme'
import type { SiteThemeTokenKey } from '@/types/payload'

export type SiteThemePreset = {
  key: string
  swatches: string[]
  themes: Record<SiteTheme, Partial<Record<SiteThemeTokenKey, string>>>
}

export const themePresets: SiteThemePreset[] = [
  {
    key: 'goose',
    swatches: ['#ffffff', '#315ef4', '#10b981', '#1b1b1b'],
    themes: {
      'gf-light': {
        'color-base-100': '#ffffff',
        'color-base-200': '#f8fafc',
        'color-base-300': '#f1f5f9',
        'color-base-content': '#111827',
        'color-icon-muted': '#64748b',
        'color-line': '#e2e8f0',
        'color-primary': '#315ef4',
        'color-primary-content': '#ffffff',
        'color-secondary': '#f0f4f8',
        'color-secondary-content': '#1f2937',
        'color-accent': '#10b981',
        'color-accent-content': '#052e2b',
        'color-neutral': '#1f2937',
        'color-neutral-content': '#ffffff',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#16a34a',
        'color-success-content': '#f0fdf4',
        'color-warning': '#f59e0b',
        'color-warning-content': '#fffbeb',
        'color-error': '#dc2626',
        'color-error-content': '#fef2f2',
      },
      'gf-dark': {
        'color-base-100': '#1b1b1b',
        'color-base-200': '#111111',
        'color-base-300': '#2b2b2b',
        'color-base-content': '#eeeeee',
        'color-icon-muted': '#b5b5b5',
        'color-line': '#3d3d3d',
        'color-primary': '#68a1ff',
        'color-primary-content': '#111111',
        'color-secondary': '#2b2b2b',
        'color-secondary-content': '#eeeeee',
        'color-accent': '#31d97b',
        'color-accent-content': '#111111',
        'color-neutral': '#eeeeee',
        'color-neutral-content': '#111111',
        'color-info': '#6fb7ff',
        'color-info-content': '#111111',
        'color-success': '#3ee7a7',
        'color-success-content': '#111111',
        'color-warning': '#ffd166',
        'color-warning-content': '#111111',
        'color-error': '#ff7a8a',
        'color-error-content': '#111111',
      },
    },
  },
  {
    key: 'clean',
    swatches: ['#fbfdff', '#2563eb', '#14b8a6', '#101418'],
    themes: {
      'gf-light': {
        'color-base-100': '#fbfdff',
        'color-base-200': '#f3f6fa',
        'color-base-300': '#e8eef5',
        'color-base-content': '#172033',
        'color-icon-muted': '#6b778a',
        'color-line': '#d9e1ec',
        'color-primary': '#2563eb',
        'color-primary-content': '#ffffff',
        'color-secondary': '#e8eef5',
        'color-secondary-content': '#1e293b',
        'color-accent': '#14b8a6',
        'color-accent-content': '#042f2e',
        'color-neutral': '#1e293b',
        'color-neutral-content': '#ffffff',
        'color-info': '#0284c7',
        'color-info-content': '#eff6ff',
        'color-success': '#059669',
        'color-success-content': '#ecfdf5',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#e11d48',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#101418',
        'color-base-200': '#0b0f13',
        'color-base-300': '#1a2028',
        'color-base-content': '#f4f7fb',
        'color-icon-muted': '#9aa8b8',
        'color-line': '#2a3440',
        'color-primary': '#60a5fa',
        'color-primary-content': '#07111f',
        'color-secondary': '#1f2937',
        'color-secondary-content': '#e5edf6',
        'color-accent': '#2dd4bf',
        'color-accent-content': '#031f1d',
        'color-neutral': '#e5edf6',
        'color-neutral-content': '#0b0f13',
        'color-info': '#38bdf8',
        'color-info-content': '#07111f',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'warm',
    swatches: ['#fffaf4', '#b45309', '#0f766e', '#15110d'],
    themes: {
      'gf-light': {
        'color-base-100': '#fffaf4',
        'color-base-200': '#f7efe3',
        'color-base-300': '#eadfce',
        'color-base-content': '#2a2118',
        'color-icon-muted': '#8a7662',
        'color-line': '#dfd1bf',
        'color-primary': '#b45309',
        'color-primary-content': '#fff7ed',
        'color-secondary': '#f1e4d3',
        'color-secondary-content': '#3b2f23',
        'color-accent': '#0f766e',
        'color-accent-content': '#ecfeff',
        'color-neutral': '#3b2f23',
        'color-neutral-content': '#fffaf4',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#15803d',
        'color-success-content': '#f0fdf4',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#be123c',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#15110d',
        'color-base-200': '#0f0c09',
        'color-base-300': '#241c15',
        'color-base-content': '#f7efe6',
        'color-icon-muted': '#b8a895',
        'color-line': '#3a2e22',
        'color-primary': '#f59e0b',
        'color-primary-content': '#1f1300',
        'color-secondary': '#2b2118',
        'color-secondary-content': '#f7efe6',
        'color-accent': '#2dd4bf',
        'color-accent-content': '#031f1d',
        'color-neutral': '#f7efe6',
        'color-neutral-content': '#15110d',
        'color-info': '#60a5fa',
        'color-info-content': '#061224',
        'color-success': '#4ade80',
        'color-success-content': '#061a0f',
        'color-warning': '#facc15',
        'color-warning-content': '#211a00',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'deep',
    swatches: ['#f7f8fa', '#4f46e5', '#06b6d4', '#080808'],
    themes: {
      'gf-light': {
        'color-base-100': '#f7f8fa',
        'color-base-200': '#eef1f5',
        'color-base-300': '#dfe5ee',
        'color-base-content': '#101218',
        'color-icon-muted': '#667085',
        'color-line': '#d6dde8',
        'color-primary': '#4f46e5',
        'color-primary-content': '#ffffff',
        'color-secondary': '#e8ebf3',
        'color-secondary-content': '#111827',
        'color-accent': '#06b6d4',
        'color-accent-content': '#06242a',
        'color-neutral': '#111827',
        'color-neutral-content': '#ffffff',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#16a34a',
        'color-success-content': '#f0fdf4',
        'color-warning': '#eab308',
        'color-warning-content': '#1f1600',
        'color-error': '#e11d48',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#080808',
        'color-base-200': '#050505',
        'color-base-300': '#171717',
        'color-base-content': '#f5f5f5',
        'color-icon-muted': '#a3a3a3',
        'color-line': '#2a2a2a',
        'color-primary': '#818cf8',
        'color-primary-content': '#080808',
        'color-secondary': '#191919',
        'color-secondary-content': '#f5f5f5',
        'color-accent': '#22d3ee',
        'color-accent-content': '#071216',
        'color-neutral': '#f5f5f5',
        'color-neutral-content': '#080808',
        'color-info': '#60a5fa',
        'color-info-content': '#07111f',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'cupcake',
    swatches: ['#fff7f3', '#f472b6', '#fbbf24', '#2d1b2f'],
    themes: {
      'gf-light': {
        'color-base-100': '#fff7f3',
        'color-base-200': '#fceee9',
        'color-base-300': '#f5ddd7',
        'color-base-content': '#2d1b2f',
        'color-icon-muted': '#9a748a',
        'color-line': '#ecd2cc',
        'color-primary': '#f472b6',
        'color-primary-content': '#3b0824',
        'color-secondary': '#fef3c7',
        'color-secondary-content': '#3a2602',
        'color-accent': '#7dd3fc',
        'color-accent-content': '#082f49',
        'color-neutral': '#2d1b2f',
        'color-neutral-content': '#fff7f3',
        'color-info': '#38bdf8',
        'color-info-content': '#082f49',
        'color-success': '#34d399',
        'color-success-content': '#062c1f',
        'color-warning': '#fbbf24',
        'color-warning-content': '#3a2602',
        'color-error': '#fb7185',
        'color-error-content': '#3a0711',
      },
      'gf-dark': {
        'color-base-100': '#2d1b2f',
        'color-base-200': '#211323',
        'color-base-300': '#3a2540',
        'color-base-content': '#fff0f7',
        'color-icon-muted': '#d7aec7',
        'color-line': '#4e344f',
        'color-primary': '#f9a8d4',
        'color-primary-content': '#2d061a',
        'color-secondary': '#facc15',
        'color-secondary-content': '#211a00',
        'color-accent': '#7dd3fc',
        'color-accent-content': '#082f49',
        'color-neutral': '#fff0f7',
        'color-neutral-content': '#2d1b2f',
        'color-info': '#7dd3fc',
        'color-info-content': '#082f49',
        'color-success': '#86efac',
        'color-success-content': '#052e16',
        'color-warning': '#fde047',
        'color-warning-content': '#211a00',
        'color-error': '#fda4af',
        'color-error-content': '#3a0711',
      },
    },
  },
  {
    key: 'retro',
    swatches: ['#f3ead7', '#b45309', '#0f766e', '#2b2118'],
    themes: {
      'gf-light': {
        'color-base-100': '#f3ead7',
        'color-base-200': '#eadfc8',
        'color-base-300': '#d9c9aa',
        'color-base-content': '#2b2118',
        'color-icon-muted': '#84715a',
        'color-line': '#d2bea0',
        'color-primary': '#b45309',
        'color-primary-content': '#fff7ed',
        'color-secondary': '#facc15',
        'color-secondary-content': '#352408',
        'color-accent': '#0f766e',
        'color-accent-content': '#ecfeff',
        'color-neutral': '#2b2118',
        'color-neutral-content': '#f3ead7',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#15803d',
        'color-success-content': '#f0fdf4',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#b91c1c',
        'color-error-content': '#fef2f2',
      },
      'gf-dark': {
        'color-base-100': '#2b2118',
        'color-base-200': '#1d1711',
        'color-base-300': '#3a2c20',
        'color-base-content': '#f8ead4',
        'color-icon-muted': '#c4ad90',
        'color-line': '#50402f',
        'color-primary': '#f59e0b',
        'color-primary-content': '#211300',
        'color-secondary': '#fde047',
        'color-secondary-content': '#211a00',
        'color-accent': '#2dd4bf',
        'color-accent-content': '#031f1d',
        'color-neutral': '#f8ead4',
        'color-neutral-content': '#2b2118',
        'color-info': '#60a5fa',
        'color-info-content': '#061224',
        'color-success': '#4ade80',
        'color-success-content': '#061a0f',
        'color-warning': '#facc15',
        'color-warning-content': '#211a00',
        'color-error': '#f87171',
        'color-error-content': '#230707',
      },
    },
  },
  {
    key: 'synthwave',
    swatches: ['#1a103d', '#e879f9', '#22d3ee', '#090313'],
    themes: {
      'gf-light': {
        'color-base-100': '#fbf7ff',
        'color-base-200': '#f2e8ff',
        'color-base-300': '#e4d4ff',
        'color-base-content': '#21143f',
        'color-icon-muted': '#7c6f9d',
        'color-line': '#d8c6f5',
        'color-primary': '#9333ea',
        'color-primary-content': '#ffffff',
        'color-secondary': '#f0abfc',
        'color-secondary-content': '#3b0764',
        'color-accent': '#06b6d4',
        'color-accent-content': '#06242a',
        'color-neutral': '#21143f',
        'color-neutral-content': '#fbf7ff',
        'color-info': '#38bdf8',
        'color-info-content': '#082f49',
        'color-success': '#22c55e',
        'color-success-content': '#052e16',
        'color-warning': '#f59e0b',
        'color-warning-content': '#211300',
        'color-error': '#f43f5e',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#090313',
        'color-base-200': '#05010b',
        'color-base-300': '#1a103d',
        'color-base-content': '#f7e8ff',
        'color-icon-muted': '#b9a6d8',
        'color-line': '#34205c',
        'color-primary': '#e879f9',
        'color-primary-content': '#2e063d',
        'color-secondary': '#7c3aed',
        'color-secondary-content': '#f7e8ff',
        'color-accent': '#22d3ee',
        'color-accent-content': '#041216',
        'color-neutral': '#f7e8ff',
        'color-neutral-content': '#090313',
        'color-info': '#38bdf8',
        'color-info-content': '#041216',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#facc15',
        'color-warning-content': '#211a00',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'aqua',
    swatches: ['#ecfeff', '#0891b2', '#6366f1', '#06151d'],
    themes: {
      'gf-light': {
        'color-base-100': '#ecfeff',
        'color-base-200': '#dff8fb',
        'color-base-300': '#c8eef4',
        'color-base-content': '#083344',
        'color-icon-muted': '#4f7e89',
        'color-line': '#b8e1ea',
        'color-primary': '#0891b2',
        'color-primary-content': '#ecfeff',
        'color-secondary': '#e0e7ff',
        'color-secondary-content': '#1e1b4b',
        'color-accent': '#6366f1',
        'color-accent-content': '#ffffff',
        'color-neutral': '#083344',
        'color-neutral-content': '#ecfeff',
        'color-info': '#0284c7',
        'color-info-content': '#eff6ff',
        'color-success': '#059669',
        'color-success-content': '#ecfdf5',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#e11d48',
        'color-error-content': '#fff1f2',
      },
      'gf-dark': {
        'color-base-100': '#06151d',
        'color-base-200': '#031015',
        'color-base-300': '#0d2633',
        'color-base-content': '#e6fbff',
        'color-icon-muted': '#8fc5d0',
        'color-line': '#1b4050',
        'color-primary': '#22d3ee',
        'color-primary-content': '#041216',
        'color-secondary': '#312e81',
        'color-secondary-content': '#eef2ff',
        'color-accent': '#818cf8',
        'color-accent-content': '#080b2b',
        'color-neutral': '#e6fbff',
        'color-neutral-content': '#06151d',
        'color-info': '#38bdf8',
        'color-info-content': '#041216',
        'color-success': '#2dd4bf',
        'color-success-content': '#031f1d',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#fb7185',
        'color-error-content': '#23070d',
      },
    },
  },
  {
    key: 'forest',
    swatches: ['#f7fbf6', '#166534', '#65a30d', '#07120b'],
    themes: {
      'gf-light': {
        'color-base-100': '#f7fbf6',
        'color-base-200': '#edf5ea',
        'color-base-300': '#dcead7',
        'color-base-content': '#142016',
        'color-icon-muted': '#64745f',
        'color-line': '#cfddc9',
        'color-primary': '#166534',
        'color-primary-content': '#f0fdf4',
        'color-secondary': '#e5f0df',
        'color-secondary-content': '#1f2a1f',
        'color-accent': '#65a30d',
        'color-accent-content': '#111a05',
        'color-neutral': '#1f2a1f',
        'color-neutral-content': '#f7fbf6',
        'color-info': '#2563eb',
        'color-info-content': '#eff6ff',
        'color-success': '#15803d',
        'color-success-content': '#f0fdf4',
        'color-warning': '#d97706',
        'color-warning-content': '#fffbeb',
        'color-error': '#b91c1c',
        'color-error-content': '#fef2f2',
      },
      'gf-dark': {
        'color-base-100': '#07120b',
        'color-base-200': '#040b06',
        'color-base-300': '#122019',
        'color-base-content': '#edf7ee',
        'color-icon-muted': '#9caf9b',
        'color-line': '#25372a',
        'color-primary': '#4ade80',
        'color-primary-content': '#041007',
        'color-secondary': '#18271d',
        'color-secondary-content': '#edf7ee',
        'color-accent': '#a3e635',
        'color-accent-content': '#101a04',
        'color-neutral': '#edf7ee',
        'color-neutral-content': '#07120b',
        'color-info': '#60a5fa',
        'color-info-content': '#061224',
        'color-success': '#34d399',
        'color-success-content': '#061f18',
        'color-warning': '#fbbf24',
        'color-warning-content': '#211300',
        'color-error': '#f87171',
        'color-error-content': '#230707',
      },
    },
  },
].map((preset) => ({
  ...preset,
  themes: {
    'gf-light': {
      ...preset.themes['gf-light'],
      'radius-selector': '0.5rem',
      'radius-field': '0.5rem',
      'radius-box': '0.5rem',
      'size-selector': '0.25rem',
      'size-field': '0.25rem',
      border: '1px',
      depth: '1',
      noise: '0',
    },
    'gf-dark': {
      ...preset.themes['gf-dark'],
      'radius-selector': '0.5rem',
      'radius-field': '0.5rem',
      'radius-box': '0.5rem',
      'size-selector': '0.25rem',
      'size-field': '0.25rem',
      border: '1px',
      depth: '1',
      noise: '0',
    },
  },
}))
